### ISSUE TITLE
Process getting Killed/stopped/restarted because out of RAM

### ISSUE THREAD

**Issue by FieryAery** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#101]
Thank you this extension prevent out of VRAM cuda error but then new issue occur. I only have 13-16gb ram and the Tiled vae process is getting killed midway when generating 3k images. Is this known limitation or do I miss something here?

**Comment by pkuliyi2015** [comment]
If you don't have enough RAM you need to keep the Fast Encoder and Fast Decoder enabled and disable the Encoder Color Fix. Legacy mode and Color fix both lead to much more RAM consumption.
