### ISSUE TITLE
勾选算法就报错，输出图片没有放大

### ISSUE THREAD

**Issue by wzddl** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#106]
勾选算法就报错，输出图片没有放大，这啥情况？

控制台输出如下:

`venv "E:\SD-webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ae337fa39b6d4598b377ff312c53b14c15142331
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --medvram --use-cpu interrogate --disable-safe-unpickle --disable-nan-check --precision full --no-half
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [9d8bb7df43] from E:\SD-webui\stable-diffusion-webui-directml\models\Stable-diffusion\perfectdeliberate_V10.safetensors
Creating model from config: E:\SD-webui\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: E:\SD-webui\stable-diffusion-webui-directml\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(1): EasyNegative
Model loaded in 2.7s (load weights from disk: 0.2s, create model: 0.5s, apply weights to model: 1.6s, load VAE: 0.3s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.2s (import torch: 3.6s, import gradio: 2.1s, import ldm: 0.8s, other imports: 2.1s, setup codeformer: 0.2s, load scripts: 2.6s, load SD checkpoint: 3.0s, create ui: 0.5s, gradio launch: 0.2s).
[Tiled Diffusion] upscaling image with R-ESRGAN 4x+...
Error running process: E:\SD-webui\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\tilediffusion.py
Traceback (most recent call last):
  File "E:\SD-webui\stable-diffusion-webui-directml\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\SD-webui\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\tilediffusion.py", line 302, in process
    image = upscaler.scaler.upscale(init_img, scale_factor, upscaler.data_path)
  File "E:\SD-webui\stable-diffusion-webui-directml\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "E:\SD-webui\stable-diffusion-webui-directml\modules\realesrgan_model.py", line 112, in do_upscale
    upsampler = RealESRGANer(
  File "E:\SD-webui\stable-diffusion-webui-directml\venv\lib\site-packages\realesrgan\utils.py", line 63, in __init__
    loadnet = torch.load(model_path, map_location=torch.device('cpu'))
  File "E:\SD-webui\stable-diffusion-webui-directml\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "E:\SD-webui\stable-diffusion-webui-directml\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "E:\SD-webui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\SD-webui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

[Tiled VAE] VAE is on CPU. Please enable 'Move VAE to GPU' to use Tiled VAE.
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.59s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.53s/it]
T`

**Comment by wzddl** [comment]
显卡是: A卡 6650XT，大佬，那你能帮帮我嘛

**Comment by pkuliyi2015** [comment]
你的realesrgan放大器有问题。换一个即可

**Comment by wzddl** [comment]
> 你的realesrgan放大器有问题。换一个即可
这样啊，感谢
我想手动修复一下放大算法的问题，不知道应该检查那些文件，去哪里下载
此前的脸部修复和反推都因为安装过程中没有下载完整 不能正常用，然后我一点点找答案修复好的

**Comment by pkuliyi2015** [comment]
models/RealESRGAN/ 下的文件 删了重下
