### ISSUE TITLE
Memory leak when using LoRA

### ISSUE THREAD

**Issue by Susanoo1337** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#116]
When using LoRA or LyCORIS either with multidiffusion or region control, the LoRA get loaded in at every sampling step and do not get unloaded, this happens until CUDA runs out of memory.
This does not happen without LoRA at the same settings.

**Comment by pkuliyi2015** [comment]
I tested but didn't find any VRAM Leakage.

Specifically, I write a custom script to run 1000000 steps on an 1024 * 768 image with regional control KoreanDollLikeness. I don't install any other extension; If there is any leakage it should use up my VRAM. But it doesn't, it just steadily consume me 4079MB VRAM. 

![image](https://user-images.githubusercontent.com/59076257/230788301-8ee08d64-0ef2-4af3-b1c8-1c806d97869e.png)


So please check again if the leakage problem comes from other extensions especially LoCORIS (I didn't heard this before).

**Comment by Susanoo1337** [comment]
Checked for compatibility with the locon extension, that seems to have been the issue as disabling it resolved the problem. Thanks for the advice.
