### ISSUE TITLE
RuntimeError: shape '[1, 32, 1, 1, 1]' is invalid for input of size 0是什么问题啊，好像只有win下的amd用户会出现

### ISSUE THREAD

**Issue by sorryhorizonTT** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#117]

**Comment by pkuliyi2015** [comment]
这个问题需要一个懂得python调试且用AMD的佬来解决。我没有AMD卡也不太可能花时间远程调试，所以一直搁置至今。

**Comment by smionli** [comment]
是direct-ml的事情，你更新到最新的directml，就会解决这个问题了，我这边是6700xt就是这样解决的

**Comment by 941641403** [comment]
我安装了最新的directml还是没解决

**Comment by Kahsolt** [comment]
More screenshots, console error logs, webui error info, traceback is needed to diagnose.
Since no more updates on this thread, temporarily close it.
