### ISSUE TITLE
How to use extension in API "script_name"

### ISSUE THREAD

**Issue by crypticsymmetry** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#12]
hello, thanks for the awesome extension. I am trying to use it as a script in the api and i keep getting this error?

Error from my web apps Chrome developer tools network console:
```
{"message":"Cannot read properties of undefined (reading '0')"}
```
this same message happened with "Ultimate SD upscale" as well, but it ended up printing the below error at some point, and i just added the proper "script_args" to get it to work.

is this the same issue? as i tried to add the args to match what was in "multidiffusion.py" "process" function and it didnt work. Any Ideas? Thank you!

error for Ultimate SD gave this:
```
TypeError: Script.run() missing 18 required positional arguments: '_', 'tile_width', 'tile_height', 'mask_blur', 'padding', 'seams_fix_width', 'seams_fix_denoise', 'seams_fix_padding', 'upscaler_index', 'save_upscaled_image', 'redraw_mode', 'save_seams_fix_image', 'seams_fix_mask_blur', 'seams_fix_type', 'target_size_type', 'custom_width', 'custom_height', and 'custom_scale'
```
then i added these args to script_args and it worked:
```
script_name: 'MultiDiffusion',
script_args: [
imageBase64, 608, 608, 8, 32, 64, 0.35, 16,
    3, 'True', 1, "False", 4,
    0, "From img2img2 settings", 1512, 1512, 2
  ],
```

**Comment by pkuliyi2015** [comment]
Interesting. I never use API calls and need to have an investigate in this question.

**Comment by crypticsymmetry** [comment]
It ended up working with "alwayson_scripts" 

```
alwayson_scripts: {
        "Tiled Diffusion": {
          "args": [
            "True", "Mixture of Diffusers",
            "False", "True", 512, 512,
            96, 96, 48, 3,
            "4x-UltraSharp", 2,
            "False",
            "False", 1, null]
        },
        "Tiled VAE": {
          "args": ["True", "False", "True", "True", "False", 1536, 112]
        }
      }
```
