### ISSUE TITLE
图片种子中未带有扩展的参数信息

### ISSUE THREAD

**Issue by iconnoci** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#121]
使用图片浏览器查看图片的生成参数 ，发现里边并没有各个区域的提示词信息，导致无法 重新这张图的生成参数（原有的随机种子啊步数啊是有的 但是扩展中的参数没有，这就无法重现这张图了），希望能加入相关扩展的信息 可以重现图的生成。

**Comment by pkuliyi2015** [comment]
确认一下你是否更新到最新？我的版本应该是能写入所有信息的。

**Comment by iconnoci** [comment]
ok没有问题，是我版本在3月27号前的，更新后就有了
