### ISSUE TITLE
Hi,i don't have noise inversion

### ISSUE THREAD

**Issue by zietenL** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#123]
![image](https://user-images.githubusercontent.com/130427069/231050276-ae4ab15b-41cf-4419-940a-c5a999c7630e.png)

**Comment by PotatoBananaApple** [comment]
Hey,

It is found under "Tiled Diffusion" and only in "img2img".

**Comment by zietenL** [comment]
thank you!
