### ISSUE TITLE
在API "alwayson_scripts"使用中Tiled VAE会报错

### ISSUE THREAD

**Issue by Seedsa** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#128]
参数如下：
alwayson_scripts = {
        'Tiled Diffusion': {
          args: [
            true,
            'MultiDiffusion',
            false, 
            10, 
            1, 
            0.4, 
            64, 
            false,
            true,
            512, 
            512,
            96, 
            96,
            48,
            8, 
            'R-ESRGAN 4x+', 
            2, 
            false, 
            false,
            false,
            false,
            null,
          ],
        },
        'Tiled VAE': {
          args: [true, false, true, true, false, 2048, 128],
        },
      };

报错信息：
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', 'color_fix', 'encoder_tile_size', and 'decoder_tile_size'

**Comment by LightChaser666** [comment]
不太清楚这是为什么。请问有具体细节么？

**Comment by WeiWenxing** [comment]
从哪里可以看到对应的参数的名称和含义啊

**Comment by dchatel** [comment]
tile vae has the wrong order.
It should be this:

True,   # "enabled": 
2048,   # "encoder_tile_size":
128,    # "decoder_tile_size":
True,   # "vae_to_gpu":
True,   # "fast_decoder":
True,   # "fast_encoder":
False,  # "color_fix":

**Comment by Seedsa** [comment]
> 

thansk!
