### ISSUE TITLE
Remove xformers dependency?

### ISSUE THREAD

**Issue by Razunter** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#130]
Don't know if it is possible to remove xformers dependency, but currently `vae_optimize.py` crashes without xformers and Torch 2.0 is fast enough to work without it.

Testing on this fork: https://github.com/vladmandic/automatic/
`NameError: name 'xformers' is not defined`

**Comment by vladmandic** [comment]
more specifically, issue is not loading xformers (thats in try/except block), but blindly assuming that if any MemoryAttention is present, its xformers (when in reality it could be anything).

Simple additional `and` statement to check if xformers are available here should do the trick:

https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/blob/70ca3c773199130462b6651364dbd133041be73a/scripts/vae_optimize.py#L192-L197

**Comment by pkuliyi2015** [comment]
I see this but I have to determine what attention is that user use. I wrote this extension a month ago，and at that time I don't know sdp.

**Comment by vladmandic** [comment]
```python
from modules import sd_hijack
print(sd_hijack.model_hijack.optimization_method)
```

its just a string, possible values are in `['none', 'sdp-no-mem', 'sdp', 'xformers', ''sub-quadratic', 'v1', 'invokeai', 'doggettx'`

**Comment by pkuliyi2015** [comment]
Thanks for your guidance. I make an adaptation in the dev branch. Would you mind to have a test? I don't have available machine for a torch 2.0 installation.

**Comment by pkuliyi2015** [comment]
I'm also trying to find my friend for a test.

**Comment by LightChaser666** [comment]
Fixed with thanks.
