### ISSUE TITLE
ComfyUI support request

### ISSUE THREAD

**Issue by lixinyiCQU** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#131]
I'm using ComfyUI in my project and I think it would be great if you could add this upscaler to ComfyUI that allows for more intuitive control of the image. This would improve my workflow and make it easier for me to use the upscaler effectively.

**Comment by Kahsolt** [comment]
try use this [https://github.com/BlenderNeko/ComfyUI_TiledKSampler](https://github.com/BlenderNeko/ComfyUI_TiledKSampler)
