### ISSUE TITLE
[Tiled VAE]: Tiled VAE is not needed on Mac. Skip loading...

### ISSUE THREAD

**Issue by JackMT** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#133]
It can't be used on a mac without a GPU, right?

**Comment by yamibo** [comment]
我也碰到了同样的情况，mac下没有Tiled VAE模块，
是因为该模块在mac下无法使用，还是该模块在mac不需要？同一台电脑在linux下是正常的。
