### ISSUE TITLE
Tiled VAE Hi Res Fix Generating Black Images

### ISSUE THREAD

**Issue by boricuapab** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#135]
Hi,

When using the Tiled VAE options with high res fix, I get black images when using text to image.

![tileVAESDSettings](https://user-images.githubusercontent.com/61924816/232613458-b64839a6-a090-4a57-ad41-e1d150a2cc5f.PNG)

![tileVAESettings](https://user-images.githubusercontent.com/61924816/232613498-d093c733-2b79-4c03-b153-a64e56bcdd70.PNG)

![args](https://user-images.githubusercontent.com/61924816/232613523-f39a53f8-f2f5-4617-becc-e5945c4d78d6.PNG)

![gradioSettings](https://user-images.githubusercontent.com/61924816/232613552-a05896d5-9ab0-448d-afb7-ae9fca98d93c.PNG)

**Comment by wangyue-gagua** [comment]
Out of memory, so you get the black image. Hires.fix and Tiled diffusion are two different upscale method. Be caution to enable both of them. If you don't have enough memory is better to use Tiled diffusion with Tiled VAE.

**Comment by boricuapab** [comment]
I uninstalled xformers 0.0.18 and re-installed xformers 0.0.17, and now I don't get black images even while using high res fix.

![xformers17](https://user-images.githubusercontent.com/61924816/233552460-6d21b540-9b04-4545-b720-940566af843a.PNG)

**Comment by boricuapab** [comment]
Would be great if this extension would work with xformers 0.0.18.

**Comment by boricuapab** [comment]
working with torch 2

and xformers 0.0.20

![worksTorch2](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/61924816/ae1860a4-b04d-47dd-bfbc-ff553818c3ea)
