### ISSUE TITLE
请问下在mac上是使用不了Tiled VAE吗？

### ISSUE THREAD

**Issue by Stanley-baby** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#137]
请问下在mac上是使用不了Tiled VAE吗？终端显示不加载，然后界面没有显示。
<img width="653" alt="Xnip2023-04-20_03-09-51" src="https://user-images.githubusercontent.com/58399659/233176240-58b929e2-4a8a-4a05-b255-746e1cc6a1ee.png">

**Comment by wangyue-gagua** [comment]
大概是因为Mac共用显存和内存吧

**Comment by xsstomy** [comment]
![image](https://user-images.githubusercontent.com/8943787/233785452-40b9dd00-7ba9-4cc3-b4c6-8d1adbaad974.png)
+ mac m1 pro ,没有Tiled VAE 界面，是不能在 mac m1 上面使用嘛？

**Comment by fallbort** [comment]
同问

**Comment by pkuliyi2015** [comment]
这个之后可以解决 现在身体不太舒服
