### ISSUE TITLE
Tiled VAE do nothing.

### ISSUE THREAD

**Issue by IgorDyx** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#141]
Tiled VAE is just stretches the image. I stretched the same image in photoshop and had the same result. What am I doing wrong? If I add some "Denoising strength" in "Hires. fix" I start to get different pictures. In "Tiled Diffusion" I get completely different pictures. Is there a way to get the same upscaled picture?

**Comment by Kahsolt** [comment]
You'd probably misunderstanded what tile diff & tile vae is actually for, see discussions #35
