### ISSUE TITLE
multidiffusion causes webui server startup error on systems with cpu only

### ISSUE THREAD

**Issue by vladmandic** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#142]
if you don't have cpu-only system, to reproduce you can run `webui --use-cpu all` (mostly used for testing).  
`multidiffusion` fails during initialization, it doesn't even have to be enabled/active.

> Calling script: /automatic/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py/ui
> ValueError: Expected a cuda device, but got: cpu

traceback is not really helpful as it points to:

```log
│ /automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py:691 in ui
│   690 │   │   │   │   encoder_tile_size = gr.Slider(
│ ❱ 691 │   │   │   │   │   label='Encoder Tile Size', minimum=256, maximum=4096, step=16, value
│   692 │   │   │   │   decoder_tile_size = gr.Slider(
```

**Comment by pkuliyi2015** [comment]
Thanis for reminding me, I will check this in my spare time.
