### ISSUE TITLE
Check for updates --> unknown

### ISSUE THREAD

**Issue by Tobe2d** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#143]
When I try to check for update it show unknown on this extention only.

Thought to let you know as I think it is bug.

I try removing the extention and re-installing it, but it did not solve it.

![image](https://user-images.githubusercontent.com/4099839/233722488-da76a46e-4029-4511-8188-f0c4bc0ef310.png)

**Comment by Kahsolt** [comment]
This page is controlled by the webui, scripts have no way to touch.
If no further console error log is provided, we're not able to help debugging.
Just try commandline `git pull`, or I will recommend [Fork](https://git-fork.com/) as your git GUI tool :)
