### ISSUE TITLE
Upscaling gone wild. Artifacts (tile duplication?)

### ISSUE THREAD

**Issue by yalamix** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#144]
For some reason, enabling Hires. fix results in [this type of artifact (NSFW)](https://imgur.com/a/cnBZmPQ).
My command line args are `--xformers --no-half --lowvram`.
This started out of nowhere. I've been using Tiled VAE to upscale with this and other models, the same command args and it worked flawlessly. This extension is the only way for me to make high resolution images with my 6GB of VRAM, since using only the args is not enough.

My theory is that I probably installed another extension that is causing this, I'm going to remove them one by one to see if that solves this, but I wanted to create this issue in case someone else already knew how to solve it.

**Comment by andupotorac** [comment]
Please add this to the main page, and explain how one should select Upscaler and Denoise Strength for T2I, if Hires can't be selected at the same time.
