### ISSUE TITLE
tiled diffusion upscale 无效，是否配置有问题？

### ISSUE THREAD

**Issue by boboarts** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#148]
因为显卡内存只有 4g 找到这个插件，各种测试均是无效，不知道是哪里没设置对。
我生成了 512 的图像，到 img2img 里勾选了 tiled diffusion 想扩大的 1024，抱错仍然是内存不够。
![image](https://user-images.githubusercontent.com/1680702/234211105-37581f9b-a805-4074-a63d-462c5e6e2422.png)
![image](https://user-images.githubusercontent.com/1680702/234211203-1b494350-8bcb-4b34-ae18-7f0bac0e0f59.png)

**Comment by pkuliyi2015** [comment]
你vae炸了显存，和tiled diffusion有什么关系。

打开tired VAE的开关，依然炸的话，自行调节一下tiled vae的数值。

**Comment by boboarts** [comment]
![image](https://user-images.githubusercontent.com/1680702/234261525-3787e996-65e6-4560-9b9e-6f47b529ab0e.png)
不太明白 如果显存不足 到底要不要开  tiled vae，目前没开，也是不行。
