### ISSUE TITLE
Tiled Diffusion安装了，Tiled VAE没有，怎么回事，imac

### ISSUE THREAD

**Issue by GavinnnnN** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#150]
<img width="1142" alt="截屏2023-04-28 15 28 53" src="https://user-images.githubusercontent.com/30067082/235083230-5187ec46-9de3-450b-a403-33b9d8774a48.png">

**Comment by soulwait** [comment]
M1Max同问题，应该是作者还做mac的版本。
