### ISSUE TITLE
It was working normal, than something happened and I'm getting this error with any settings. 

### ISSUE THREAD

**Issue by IgorDyx** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#151]
RuntimeError: CUDA out of memory. Tried to allocate 9.15 GiB (GPU 0; 12.00 GiB total capacity; 2.23 GiB already allocated; 7.49 GiB free; 2.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Time taken: 16.92sTorch active/reserved: 2328/2364 MiB, Sys VRAM: 12288/12288 MiB (100.0%)
![Capture](https://user-images.githubusercontent.com/49569662/235291716-364c7a9f-2a95-480d-9320-0bd4c2878d12.PNG)

**Comment by Kahsolt** [comment]
Are you working with ControlNet? It is known that the ControlNet script has some VRAM leakage issues and might cause this OOM problem.
Can you run any a simple case on your machine? e.g. no extras networks, no tiled difffusion, only a large canvas 2048x2048 with tiled vae enabled.

FYI, 12G VRAM should at least support `decoder tile size=128` ;)
