### ISSUE TITLE
今天更新后出问题了，在局部重绘时勾上tiled vae会中断并报错

### ISSUE THREAD

**Issue by dajusha** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#154]
RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1.  Target sizes: [1, 3, 76, 100].  Tensor sizes: [8, 76, 100]

不启用它才能继续，但出图数目受影响。

**Comment by dajusha** [comment]
实测，vae_optimize.py 这个文件退回到一天前（大约两周前更新）的版本(sha256: da5d9419f52661e714bd60bc77ceee1f0f35074cb9ab5e17931ca1652b413b9d )，问题消失了。

**Comment by luckyray-fan** [comment]
碰到了同样的问题

**Comment by Kahsolt** [comment]
PR #157 is rollbacked, now everything should return normal.
Please test the latest commit, close the thread or continue reporting bugs, patiently ;)

Thanks for your support!
