### ISSUE TITLE
error since last update

### ISSUE THREAD

**Issue by Jos3lgd** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#155]
RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1. Target sizes: [1, 3, 88, 96]. Tensor sizes: [8, 88, 96]

**Comment by dajusha** [comment]
get this file, replace the updated one, https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/raw/71dd5c539050cae86ba23eee29239ac7a4432360/scripts/vae_optimize.py
and waiting for fix

**Comment by furana93** [comment]
> get this file, replace the updated one, https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/raw/71dd5c539050cae86ba23eee29239ac7a4432360/scripts/vae_optimize.py and waiting for fix

Thanks, it works after i put it on \stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts

**Comment by shinthotrang** [comment]
> get this file, replace the updated one, https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/raw/71dd5c539050cae86ba23eee29239ac7a4432360/scripts/vae_optimize.py and waiting for fix

Sorry, I'm noob at this kind of thing. How can I download this? I have tried git pull and git clone.

**Comment by LieDeath** [comment]
> > get this file, replace the updated one, https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/raw/71dd5c539050cae86ba23eee29239ac7a4432360/scripts/vae_optimize.py and waiting for fix
> 
> Sorry, I'm noob at this kind of thing. How can I download this? I have tried git pull and git clone.

put on your VPN

**Comment by LieDeath** [comment]
same error, caused by encoder process. might be fall back to 5da750b is better

**Comment by Kahsolt** [comment]
PR #157 is rollbacked, now everything should return normal.
Please test the latest commit, close the thread or continue reporting bugs, patiently ;)

Thanks for your support!
