### ISSUE TITLE
Please change Accordion default open to False

### ISSUE THREAD

**Issue by tkgix** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#16]
Thank you for your hard work.

I fully understand your desire to encourage new extension, but I don't think it's right to inconvenience using the UI.

multidiffusion.py. Line 293.
with gr.Accordion('MultiDiffusion', open=True):

to
with gr.Accordion('MultiDiffusion', open=False):

**Comment by pkuliyi2015** [comment]
You may think I'm on purpose; but in fact, **I don't expect to "encourage new extension" in this way.** I don't get any benefit from such an open-source extension. If you use it, it's my pleasure. If you dislike it, I'm very sorry.

I use it on my own purpose and open it by default for convenience in debugging. In heavy work of development, I need to frequently restart the UI to reload my code. The default reload function of webui is broken (I don't know why), but according to another users, I have already change the enable from True to False.

 But as you suggested, I will change it to false to benefit your use. In my own version, I use True.
