### ISSUE TITLE
Repeated problems with characters

### ISSUE THREAD

**Issue by gejing3326** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#17]
Please forgive me for my poor English. When I use (mult) and (vav), I use the default, but the rendered image still repeats two people, write(1 girl) in the tag. Still useless,Then close it(mult) can have a person. How to solve it?Thank you very much.

**Comment by dill-shower** [comment]
Don't include any concrete objects in your positive prompts. Otherwise the results get ruined.
Just use something like "highres, masterpiece, best quality, ultra-detailed unity 8k wallpaper, extremely clear".

**Comment by pkuliyi2015** [comment]
Resolved with thanks. Please use the latest prompt control technique.
