### ISSUE TITLE
i can't use Noise Inversion

### ISSUE THREAD

**Issue by zietenL** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#173]
when i turn on the noise inversion,generating images results in errors

AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 's_min_uncond'

![image](https://user-images.githubusercontent.com/130427069/236388093-61cee459-1404-4150-b991-7ab8e02b28ad.png)

**Comment by Kahsolt** [comment]
In commit 174ec50af89d144d8fe889058bd622b545c177e1, we add `s_min_uncond` to support sd-webui v1.1.0
You should either update your sd-webui or rollback this repo before that commit

**Comment by zietenL** [comment]
it's worked,thank you!!!!!!!
