### ISSUE TITLE
[Feature request] support for prompt editing, wildcards, dynamic prompts extensions

### ISSUE THREAD

**Issue by halr9000** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#180]
I use a lot of features and extensions to make more complex prompts, and I suspect that MD isn't using them based on my tests. How hard would it be for you to support these sort of things? e.g.

* [Prompt Editing
](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#prompt-editing) which uses brackets to change the prompt over sampler steps
  * e.g. `ufo [ cat : 0.5 ]` will add cat to the prompt halfway through sampling
* [Dynamic Prompts extension](https://github.com/adieyal/sd-dynamic-prompts), which does some funky stuff to give you some logic control 
  * e.g. `{ red | black } background` will pick one value randomly each run, so, "red background" or "black background".
* Wildcards (used to have a separate extension, now is built-in to Dynamic Prompts)
  * e.g. use `__path/wildcard__` and a random line from the file at that path is inserted into the prompt

So instead of what I want (which I can do if I use the main prompt), what I get is:

![image](https://user-images.githubusercontent.com/18482/236688334-4d310433-7ec9-4dde-bece-0dfededf2806.png)

* too much cat :) 
* black and green
* no clue what it will try to do with the file paths, looks it stripped off the underscores and is ignoring

I think you get the idea! 

> complex, trending on artstation, best best quality,
> Negative prompt: easynegative,
> Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3185998936, Size: 910x512, Model hash: 6ac5833494, Model: sd15_perfectdeliberate_v20, Tiled Diffusion: "{'Method': 'MultiDiffusion', 'Latent tile width': 96, 'Latent tile height': 96, 'Overlap': 48, 'Tile batch size': 1, 'Region control': {'Region 1': {'enable': True, 'x': 0, 'y': 0, 'w': 0.3333, 'h': 1, 'prompt': 'ufo [ cat: 0.8 ]', 'neg_prompt': '', 'blend_mode': 'Foreground', 'feather_ratio': 0, 'seed': 2052625680}, 'Region 2': {'enable': True, 'x': 0.3333, 'y': 0, 'w': 0.3333, 'h': 1, 'prompt': 'ufo { black | green } background', 'neg_prompt': '', 'blend_mode': 'Foreground', 'feather_ratio': 0, 'seed': 3532385151}, 'Region 3': {'enable': True, 'x': 0.6666, 'y': 0, 'w': 0.3333, 'h': 1, 'prompt': 'ufo __devilkkw/composition/image_composition_angle_perspective_depth__ ', 'neg_prompt': '', 'blend_mode': 'Foreground', 'feather_ratio': 0, 'seed': 554465402}}}"
>

**Comment by Kahsolt** [comment]
Regrettable to claim that our `Region prompt control` only goes through the webui core sampling pipeline, no extensions will be enabled region by region. It is very hard to implement in that way, unless, the tiled manner is natively embedded into sd-webui's core :(

**Comment by PotatoBananaApple** [comment]
@halr9000 Check out https://github.com/opparco/stable-diffusion-webui-two-shot

 or fork https://github.com/ashen-sensored/stable-diffusion-webui-two-shot 

The fork gives ability to paint the areas.

Works together with tiling.

![image](https://user-images.githubusercontent.com/130109414/236801282-068b67ee-b704-47bb-be0c-b5f3f55c01ae.png)

![image](https://user-images.githubusercontent.com/130109414/236801311-3aaaf36e-66df-463c-bdc6-bd39187d7426.png)

**Comment by halr9000** [comment]
> Regrettable to claim that our `Region prompt control` only goes through the webui core sampling pipeline, no extensions will be enabled region by region. It is very hard to implement in that way, unless, the tiled manner is natively embedded into sd-webui's core :(

NP I figured it was non-trivial, but had to ask!
