### ISSUE TITLE
新式三合一放大法，在渐变和亮点的区域产生奇怪的纹路

### ISSUE THREAD

**Issue by dajusha** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#184]
即是在新版readme中提及的 CN1.1 + TIrs=0 + MixOfDiff 方法。
大部分图效果很好，今天的渐变色出了问题，不知道如何调整参数比较好？
颜色偏色在readme中已经提及了，不是大问题。

放大先后的部分图片如下：
![before](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/12206161/31d5de8e-fc56-46f6-8ca7-fef31330ac5a)
![after](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/12206161/07425e75-ac6b-405f-93fc-35b9f5c100be)

**Comment by pkuliyi2015** [comment]
你这个是典型的生成了水印。

请在正面prompt中加入星空描述，负面prompt中加入高权重的signature和watermark。必要时请换一个模型，有的模型作者过滤素材不很仔细，画出水印很正常。

**Comment by dajusha** [comment]
> 你这个是典型的生成了水印。
> 
> 请在正面prompt中加入星空描述，负面prompt中加入高权重的signature和watermark。必要时请换一个模型，有的模型作者过滤素材不很仔细，画出水印很正常。

原来这样……我按照原来MultiDiffusion的路数把提示框清空了再放大的……
看来现在要留着了
