### ISSUE TITLE
what's this problem?The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1. Target sizes: [1, 3, 192, 256]. Tensor sizes: [8, 192, 256]

### ISSUE THREAD

**Issue by nanakris** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#185]
MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 96x96, Tile batches: 24, Batch size: 1
[Tiled VAE]: input_size: torch.Size([1, 3, 3072, 2048]), tile_size: 2048, padding: 32
[Tiled VAE]: split to 2x1 = 2 tiles. Optimal tile size 1984x1504, original tile size 2048x2048
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 1365 x 2048 image

Arguments: ('task(z5bv50y9ggjpm6k)', 0, '8k,(RAW photo, best quality), (realistic, photo-realistic:1.2),official art, unity 8k wallpaper, ultra detailed, beautiful and aesthetic, masterpiece,A glamour portrait of a magical superheroine casting an enchanted spell, polished, fantasy inspired, whimsical color and lighting,(full body:1.2)', 'ng_deepnegative_v1_75t, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, ((monochrome)), (grayscale:1.2), skin spots, acnes, skin blemishes, age spot, nose, cropped, lowres, text, jpeg artifacts, signature, username, blurry, artist name, trademark, watermark, title, (tan, muscular, loli, petite, child, infant, toddlers, chibi, sd character:1.1), multiple view, Reference sheet, badhandv4', [], <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x163D88B7880>, None, None, None, None, None, None, 30, 15, 4, 0, 1, True, False, 1, 1, 7, 1.5, 0.75, 660219364.0, -1.0, 0, 0, 0, False, 0, 1536, 1024, 1, 0, 0, 32, 0, '', '', '', [], 0, False, 'face_yolov8n.pt', '', '', 30, 32, 0, 0, 4, 0.4, True, 0, False, 512, 512, False, 7, 'None', 1, 'None', '', '', 30, 32, 0, 0, 4, 0.4, True, 0, False, 512, 512, False, 7, 'None', 1, True, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 32, 1, 'R-ESRGAN 4x+', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, False, True, True, False, 2048, 128, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x00000163D88A6770>, <scripts.external_code.ControlNetUnit object at 0x00000163CE0575E0>, <scripts.external_code.ControlNetUnit object at 0x00000163D8721120>, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nTEST:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, None, [], 0, False, [], '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', None, 'Add Tags to Prompt', '8k,(RAW photo, best quality), (realistic, photo-realistic:1.2),official art, unity 8k wallpaper, ultra detailed, beautiful and aesthetic, masterpiece,A glamour portrait of a magical superheroine casting an enchanted spell, polished, fantasy inspired, whimsical color and lighting,(full body:1.2)', [], [], [], [], '', '', '', '', '', [], [], [], '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\img2img.py", line 181, in img2img
    processed = process_images(p)
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\processing.py", line 604, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\processing.py", line 1084, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\AI\stable-diffusion-webui_23-03-10\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui_23-03-10\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "E:\AI\stable-diffusion-webui_23-03-10\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "E:\AI\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui_23-03-10\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 377, in __call__
    return self.vae_tile_forward(x)
  File "E:\AI\stable-diffusion-webui_23-03-10\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 264, in wrapper
    ret = fn(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui_23-03-10\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 618, in vae_tile_forward
    result[:, :, out_bboxes[i][2]:out_bboxes[i][3], out_bboxes[i][0]:out_bboxes[i][1]] = crop_valid_region(tile, in_bboxes[i], out_bboxes[i], is_decoder)
RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1.  Target sizes: [1, 3, 192, 256].  Tensor sizes: [8, 192, 256]

**Comment by Kahsolt** [comment]
see #168
