### ISSUE TITLE
ControlNet' tile causes color distortion with multidiffusion when Prompt length is long

### ISSUE THREAD

**Issue by Rkkss** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#191]
https://imgsli.com/MTc3Njky
![237830537-48094931-31b2-49f6-b818-449b0e424dc2](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/127614350/c09436f6-5361-4d13-bd75-f7f866d35774)

Pictures above show the issue. I compare metadata and the only difference is usage of BREAK keyword. 
Neither of tile model nor MultiDiffusion does this when use them alone but when use together (& 'CN is more important' is set), they cause problem 

I asked CN team and they pointed to this [compatibility](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/labels/compatibility)
This is because you used "controlnet is more important" and when the token is more than 75, the combo of tiled diffusion and controlnet has a bug to disorder tiles. Removing BREAK will trigger this since it makes token longer

Tested on
Automatic 1943bfea
Auto1111 5ab7f213

Catbox files in case you want to recreate this. Loras are not needed, I've tested without using any.
Original image. Use this as base img2img/controlNET to upscale: https://files.catbox.moe/ep1a0k.png

https://files.catbox.moe/79onls.png
https://files.catbox.moe/2vqh0b.png

**Comment by lllyasviel** [comment]
perhaps we should add a note in CN or Tiled Diff to say the mode "controlnet is more important" and the Shuffle model will sometimes cause bugs. 

Everything else works very well I think.

Or we can add users to add flag --always-batch-cond-uncond but this sometimes wont work if users really OOM without instance slicing.

The cause is that CN's "controlnet is more important" and the Shuffle model needs batch cond/uncond counter https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/153

**Comment by lllyasviel** [comment]
Unfortunately, this problem is deeply inside a1111 and I do not think we have any good solution now. Perhaps the only solution is to let users know.

**Comment by Rkkss** [comment]
I think the work around is use little prompt as possible even empty prompt works.
That is for balanced and CN is more important modes

**Comment by PotatoBananaApple** [comment]
> I think the work around is use little prompt as possible even empty prompt works. That is for balanced and CN is more important modes

In the end 75 tokens is quite a lot unless you want to use 50 for quality tags. Which nowadays is not necessary.

**Comment by Rkkss** [comment]
> > I think the work around is use little prompt as possible even empty prompt works. That is for balanced and CN is more important modes
> 
> In the end 75 tokens is quite a lot unless you want to use 50 for quality tags. Which nowadays is not necessary.
It's less than 75, don't know what is the threshold but It's something 30-50 before bug kicks in. 
Also, for balance mode, cfg need to be lower than normal.

**Comment by PotatoBananaApple** [comment]
> > >> I think the work around is use little prompt as possible even empty prompt works. That is for balanced and CN is more important modes
> > >
> > > 
> > > In the end 75 tokens is quite a lot unless you want to use 50 for quality tags. Which nowadays is not necessary.
> > It's less than 75, don't know what is the threshold but It's something 30-50 before bug kicks in.
> > Also, for balance mode, cfg need to be lower than normal.

Hmm interesting, i did some testing and it got weird after 75, gotta test again. Did not test around 30-50

**Comment by Rkkss** [comment]
![00046-543210](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/127614350/d49dc465-219e-4b12-868b-5df132526d20)

Changing CN tile weight 0.6, ending step to 0.6 help. It's not perfect still, most of samplers, especially double step ones don't work :/

**Comment by pkuliyi2015** [comment]
I'd like to introduce some new technique tomorrow (05/19) with my schoolmate. It should be a competitive alternative to NI & ControlNet Tile for high-fidelity image super-resolution.

**Comment by lllyasviel** [comment]
Solved in https://github.com/Mikubill/sd-webui-controlnet/commit/539d2fc990bc592dd7e482ecabffdc511073dbed
Now controlnet directly track negative prompts to find cond-uncond
Other extensions do not need to add any codes - very clean

**Comment by lllyasviel** [comment]
This can be closed I think

**Comment by Rkkss** [comment]
> This can be closed I think

Haven't tested myself but I'll take your word for it
