### ISSUE TITLE
Reuse seed button not functional in region prompts

### ISSUE THREAD

**Issue by williamkmlau** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#193]
![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/34730446/cfa5f790-bee3-4cc5-bfb4-d2363d792de0)
this button seems to be not working, I generated an image in T2I and the region prompt seed cannot be reused, not by clicking the button, nor is the seed information retained anywhere

**Comment by xmk2222** [comment]
It blocked me too! The result of T2I is NOT reproducible at all!!!
Please solve this bug, it will be very helpful!!!
And the seed is not saved in the png info.

**Comment by xmk2222** [comment]
It is really a great extension, but I can NOT reproduce any of my job even with fixed seeds. Please help!!!

**Comment by Nott89** [comment]
hello, sorry to reopen this thread, but it seems that this bug has appeared again. I haven't used automatic1111 in a while, so I don't know if it's due to the recent switch to 1.6, but basically the problem is identical to the one described above.
