### ISSUE TITLE
CUDA out of memory using recommended settings with 24 gig of vram

### ISSUE THREAD

**Issue by crazygonuts** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#194]
I have a geforce 3090 with 24 gig of ram.  using the recommended settings it is trying to allocate 30 gig of ram.  There's a lot of parameters in this extension with no documentation or no explanation of what they do so its entirely possible i need to change one of them.  Here's what I have set:

![cuda_oom](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/131223696/2735d0a1-b4f1-46ed-bc3d-2987d609b653)

**Comment by PotatoBananaApple** [comment]
Do you have tiled VAE enabled?, also good idea to have batch size higher. I made tutorial about this extension in civitai that explains settings (mostly). The guide is made from my personal opinionated point of view and may have settings that are not the most efficient etc... Still should give general information how it works.

Also is your image size 2048 x 2048? Only use the Scale factor to scale, don't mix and match other scaling :).

https://civitai.com/models/34726/tutorial-for-multidiffusion-upscaler-for-automatic1111-detail-to-the-max

**Comment by crazygonuts** [comment]
the image is 2048 x 2560 and I am trying to scale it up 2x, yes.

**Comment by crazygonuts** [comment]
I did not have tiled vae enabled, enabling it and then drastically reducing the default value seems to have gotten me in memory.  There is no mention in the doc of what reason there would be to have this value high or low - does it matter?

**Comment by PotatoBananaApple** [comment]
> I did not have tiled vae enabled, enabling it and then drastically reducing the default value seems to have gotten me in memory. There is no mention in the doc of what reason there would be to have this value high or low - does it matter?

Lowering the VAE tile will lower the VRAM needed, but with your 24GB you should be fine with the basic settings. If you are using full live preview reduce it to pretty low, it seems to be causing quite big spikes in the VRAM usage and can cause error in middle of generation.

**Comment by crazygonuts** [comment]
I turned off live previews and with the vae tile size set to 2048 it uses 23.8 gig of ram to upscale this image.  That seems very high if I am understanding your statement correctly.  It will go down as low as 256 - if I set it that low, what does that effect?  will the image be worse?

**Comment by crazygonuts** [comment]
also I don't see how i could put the batch size bigger than 1 without running out of memory?

**Comment by PotatoBananaApple** [comment]
The Approx NN is pretty cheap and ok live preview to keep on.

Can you show image of your current settings.

**Comment by crazygonuts** [comment]
![tile_settings](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/131223696/030f3676-ffad-4894-bfe0-70e8e578280b)

should I uncheck "move vae to gpu"?

**Comment by PotatoBananaApple** [comment]
I personally use VAE decoder tile size usually 112 and encoder 2048. 

Is the usage during encoder phase, or during the generation phase? Do you have other programs hogging your VRAM? 

Also do you have xformers enabled. It reduces the VRAM usage a lot.

Tested with your exact settings and this is my usage:

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/130109414/cac74bd9-58e5-44b6-9a7a-e9096f769317)

At the encoder phase it jumped to something like 11.4GB

**Comment by crazygonuts** [comment]
The vram usage spikes during encoding and decoding to 23+ gig.

the only thing using vram is stable diffusion.  I am not using xformers, as I usually use scaled dot product as my optimization.  Is multidiffusion supposed to only be used with xformers?

**Comment by pkuliyi2015** [comment]
No, it's also OK to use SDP. But SDP takes much more VRAM, so you should lower your VAE tile size accordingly.

Lower encoder tile size (>1024) won't bring significant difference, but if it is too low, the image color will change so you have to use the encoder color fix in that case.

**Comment by PotatoBananaApple** [comment]
Is there any reason to use SDP over xformers? Have not tested it yet.

**Comment by pkuliyi2015** [comment]
> Is there any reason to use SDP over xformers? Have not tested it yet.

My friends say it is slightly faster than xformers.

**Comment by PotatoBananaApple** [comment]
Yeah seems like there is some improvement in speed https://huggingface.co/docs/diffusers/v0.16.0/optimization/torch2.0

Gotta test out and see if it is worth over the VRAM usage reduction.

**Comment by crazygonuts** [comment]
I tried with xformers, it  does not have a significant reduction in memory usage for me.
![mem](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/131223696/0cdf9183-c2d1-4f3e-a7b8-53194b6e2bb4)

I will reduce my vae settings further but it seems like the default makes it basically unusable for any card currently on the market, right?

**Comment by PotatoBananaApple** [comment]
What is the usage after decoder finishes?

**Comment by crazygonuts** [comment]
2.6

**Comment by pkuliyi2015** [comment]
> I tried with xformers, it does not have a significant reduction in memory usage for me. ![mem](https://user-images.githubusercontent.com/131223696/238115737-0cdf9183-c2d1-4f3e-a7b8-53194b6e2bb4.PNG)
> 
> I will reduce my vae settings further but it seems like the default makes it basically unusable for any card currently on the market, right?

No, the default settings assume you use a 2GB checkpoint without Lora or Controlnet. Please be aware that additional techniques will take away your VRAM

**Comment by crazygonuts** [comment]
is it control that is eating all the memory then?  I was checking "pixel perfect", should I instead pick a smaller resolution?
