### ISSUE TITLE
Great for HDRI/Equirectangular usecase

### ISSUE THREAD

**Issue by GeorgLegato** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#20]
@pkuliyi2015 this is a great extension, esp for controlling depth-maps of equirectangular/hdri like scenes.
they need a lot of resolution, 15-32k best.
Btw, how did you get into the extension-index.md of Auto1111 wiki? I try to put my Panorama-Extension there, but my post is one of thousands in the discussion section.
https://github.com/GeorgLegato/sd-webui-panorama-viever

https://www.reddit.com/r/StableDiffusion/comments/11jh9tx/call_for_betatestersdevs_panoramaviewer_extension/

my workflow so far without your extension:
https://www.reddit.com/r/StableDiffusion/comments/11jnnb7/workflow_sharks_sd1111controldepth_lighting/

---

1st trial to create 16k x 8k image for equirectangular view:
30597 steps on my 3080 12GiB Ram... °!°
![image](https://user-images.githubusercontent.com/7210708/224510730-ed3da92c-d02f-4bf2-bf82-72dfdad48b81.png)

Input Controlnet is nativ 16k x 8k HDRI image preprocessed to Depth
![image](https://user-images.githubusercontent.com/7210708/224510796-9c059753-ef15-4424-9146-649014eb2d24.png)

cya

**Comment by pkuliyi2015** [comment]
Thanks for paying attention to my work.

I didn't intentionally do anything to put my plugins into the official read me.I guess they have a github robot or some managers that consistently scan for related repos. 

But i do heard from some friends that you can fill in a form to add your plugins Into the official list.Sadly, i don't know where the form is.

**Comment by pkuliyi2015** [comment]
By the way have you done some initial tests on a smaller image (i.e., 4k) to determine your optimal tile_batch_size? If you can use a larger tile size it can be much faster.
