### ISSUE TITLE
Setting upscaler to "none" doesn't scale up the image

### ISSUE THREAD

**Issue by apinanaivot** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#201]
If you set the upscaler to "none", it doesn't rescale the image, but keeps it at the same size. This is not what should happen, it should still scale up the image using a non-neural network upscaling method (such as bilinear interpolation), like how Ultimate SD Upscale does for example. It's bad that scaling up the image only works with upscalers, as they often smooth out surfaces, making the resulting image less detailed.

**Comment by PotatoBananaApple** [comment]
Have you tried upscalers like:

4x_NMKD-Siax_200k
4x_NMKD-Superscale-Artisoftject_210000_G

**Comment by apinanaivot** [comment]
> Have you tried upscalers like:
> 
> 4x_NMKD-Siax_200k 4x_NMKD-Superscale-Artisoftject_210000_G

Yes, pretty much all AI upscalers are trained to remove noise, here is an example of the results I get with an upscaler, and without (by manually resizing the image in photoshop before using multidiffusion upscaler):

![comparison](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/12139741/d086d9a3-0ada-483c-87a0-c44f9560f190)

As you can see, while removing the noise, it also removed lots of details in the hair strands and other places, and overall made the image look less realistic.

It can't be a difficult addition to make the scale factor still work when setting the upscaler to none.

**Comment by PotatoBananaApple** [comment]
Hmm interesting.

technically you could use `resize by` and disable `Keep input image size`

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/130109414/771d2dac-2ddd-42f8-a22f-1838d2747cde)

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/130109414/8e97ee58-eb7c-4ff1-b95a-bfc0f736cbb4)

**Comment by pkuliyi2015** [comment]
> If you set the upscaler to "none", it doesn't rescale the image, but keeps it at the same size. This is not what should happen, it should still scale up the image using a non-neural network upscaling method (such as bilinear interpolation), like how Ultimate SD Upscale does for example. It's bad that scaling up the image only works with upscalers, as they often smooth out surfaces, making the resulting image less detailed.

Please select Lanczos manually. Ultimate SD Upscaler switches to Lanczos silently when you choose None. 

However, I don't do such silent switching as them, because this extension is not only an upscaler, in many cases I use it to fix the face or hands. And it will be inconvenient when I don't want to change the size of the photo, (I have to slide the scale factor to 1).

**Comment by apinanaivot** [comment]
> > If you set the upscaler to "none", it doesn't rescale the image, but keeps it at the same size. This is not what should happen, it should still scale up the image using a non-neural network upscaling method (such as bilinear interpolation), like how Ultimate SD Upscale does for example. It's bad that scaling up the image only works with upscalers, as they often smooth out surfaces, making the resulting image less detailed.
> 
> Please select Lanczos manually. Ultimate SD Upscaler switches to Lanczos silently when you choose None.
> 
> However, I don't do such silent switching as them, because this extension is not only an upscaler, in many cases I use it to fix the face or hands. And it will be inconvenient when I don't want to change the size of the photo (I have to write several more lines of code, and slide the scale factor to exactly 1 when I use. More difficult than just switch to None).

Thanks for the response and tip! I guess it's just a bit confusing that they work differently, maybe there could be an option called "don't upscale" in addition to "none", and "none" would still upscale the image for the sake of clarity and consistency.

**Comment by pkuliyi2015** [comment]
Thanks for suggestions. I will change the option names for clarity in my spare time.

**Comment by andupotorac** [comment]
> > If you set the upscaler to "none", it doesn't rescale the image, but keeps it at the same size. This is not what should happen, it should still scale up the image using a non-neural network upscaling method (such as bilinear interpolation), like how Ultimate SD Upscale does for example. It's bad that scaling up the image only works with upscalers, as they often smooth out surfaces, making the resulting image less detailed.
> 
> Please select Lanczos manually. Ultimate SD Upscaler switches to Lanczos silently when you choose None.
> 
> However, I don't do such silent switching as them, because this extension is not only an upscaler, in many cases I use it to fix the face or hands. And it will be inconvenient when I don't want to change the size of the photo (I have to write several more lines of code, and slide the scale factor to exactly 1 when I use. More difficult than just switch to None).

Are you using it with ADetailer for fixing the hands and face?

**Comment by andupotorac** [comment]
> > Hmm interesting.
> > technically you could use `resize by` and disable `Keep input image size`
> 
> No you could not, as this extension overrides that value (as it should)

See this: https://www.reddit.com/r/StableDiffusion/comments/y2mrc2/the_definitive_comparison_to_upscalers/.

For illustrations, there's a better one that he didn't tests (I checked Ultrasharp too). The best option to keep an image the same is to use 4x_foolhardy_Remacri with 0 denoise strength.

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/32bed61f-baa4-4a14-b8fa-3cf8b8c40030)


Attached examples so you can check the comparison (look at the nose):

1. 4x_foolhardy_Remacri_0 denoise
![1  4x_foolhardy_Remacri_0 denoise](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/4ace7cda-8ac2-496c-9868-05f403d13c5b)

2. realesr-general-wdn-x4v3_0 denoise
![2  realesr-general-wdn-x4v3_0 denoise](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/eb241eec-e2b1-4176-9699-6f6a2a327caa)

3. ESRGAN_4x_0 denoise
![_3  ESRGAN_4x_0 denoise](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/759df800-3a45-4b92-af8a-cf771c81e444)

4. R-ESRGAN 4x+ Anime6B_0 denoise
![4  R-ESRGAN 4x+ Anime6B_0 denoise](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/89890f21-5758-4a3a-a674-6d373cdef94c)

5. LDSR_0 denoise
![5  LDSR_0 denoise](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/efa985fa-41ee-491d-a133-15891d06d2cb)

6. 4x-UltraSharp_0 denoise
![6  4x-UltraSharp_0 denoise](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3269738/827e346c-3044-448c-b7d0-f58b856f48ca)


And here you see Tiled Upscaling applied to #1 for better details.
https://imgur.com/P6lKpbY
