### ISSUE TITLE
Not an issue! Where i can send a donation for a beer/coffe?

### ISSUE THREAD

**Issue by sebaxakerhtc** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#214]

**Comment by pkuliyi2015** [comment]
Thanks for your appreciation! I will consider it after I have some spare time

**Comment by halr9000** [comment]
I'm in.

**Comment by pkuliyi2015** [comment]
I added a Ko-fi button now, so this issue can be closed. Thanks for your appreciation and support!

**Comment by sebaxakerhtc** [comment]
> I added a Ko-fi button now, so this issue can be closed. Thanks for your appreciation and support!

First donation is on the way!

**Comment by pkuliyi2015** [comment]
Thank you very much!
