### ISSUE TITLE
大佬，为什么我出的图是烂的

### ISSUE THREAD

**Issue by wangnimaaa** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#215]
我用图生图的Tiled Diffusion出的图是烂图，参数我只调了潜变量分块(Latent tile)重叠：40，潜变量分块(Latent tile)批处理规模：5 其他我都没动过，后台也没显示爆显存之类的错误，只能重启后台才行，但是时不时烂图就很难受，希望作者大大解决。

**Comment by pkuliyi2015** [comment]
请贴烂图作为示例。烂图是黑的吗？

**Comment by Kahsolt** [comment]
No further actions, close temporarily.
