### ISSUE TITLE
Unique component ids for https://github.com/Zyin055/Config-Presets

### ISSUE THREAD

**Issue by michael-imbeault** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#218]
Hi! Fantastic extension, part of my workflow now!

Would be great to add "id" in the css for all components so that they can be targeted and saved by https://github.com/Zyin055/Config-Presets - ControlNet has them, allows me to reload all the presets in 1 button using the extension. There's a lot of them in multidiffusion and it is somewhat painful to setup everytime.

**Comment by pkuliyi2015** [comment]
I have made attemp to do it. Please see if it works now.

**Comment by michael-imbeault** [comment]
Doesn't look like it, tried to add a line referring to MD-enabled to config-txt2img-custom-tracked-components.txt in the extension folder.

For reference, controlnet ones are named something like txt2img_controlnet_ControlNet-1_controlnet_enable_checkbox

**Comment by pkuliyi2015** [comment]
This time I tried to add t2i/i2i in the elem_id. Does it work now?

**Comment by michael-imbeault** [comment]
Still not, not sure why - I tried adding MD-t2i-enabled to config-img2img-custom-tracked-components.txt and the UI for config presets doesnt show up in the main UI, meaning something is breaking it. Works fine with ControlNet, even adding custom tags for it (such as img2img_controlnet_ControlNet-0_controlnet_type_filter_radio)

**Comment by michael-imbeault** [comment]
Well, [v1.3.0] of stable-diffusion-ui added an option to edit defaults that works, so no need to finish this one from my point of view, I will switch to that, it works great.

**Comment by pkuliyi2015** [comment]
Ok. I will then see the preset problem.
