### ISSUE TITLE
When using new controlnet tile preprocessors - tile_colorfix and tile_colorfix+sharp - tiled diffusion is very very slow

### ISSUE THREAD

**Issue by crazygonuts** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#219]
using the regular tile preprocessor I can upscale a particular image in about 3 minutes.  With either of the new preprocessors the same image takes between 30 and 40 minutes.  From what I can tell, it is running a VAE encoding pass on every denoising iteration.  If this is required due to the algorithm then thats unfortunate, but it was such a huge slowdown compared to normal tile resampling that I thought it might be a bug.

**Comment by lllyasviel** [comment]
[From ControlNet] this problem is fixed in 1.1.200
We try best to test all other extensions as much as possible and solve conflicting problems

**Comment by pkuliyi2015** [comment]
> [From ControlNet] this problem is fixed in 1.1.200 We try best to test all other extensions as much as possible and solve conflicting problems

Great thanks for your consideration! I'm busy recently and cannot spend much time on this.
