### ISSUE TITLE
Feature Request: add an option force convert half

### ISSUE THREAD

**Issue by ash0080** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#22]
```
error: output type 'tensor<1x32x4x512x544xf16>' and mean type 'tensor<1x32x1x1x1xf32>' are not broadcast compatible
```

On a mac tiledVAE does not work while MultiDiffusion does

**Comment by pkuliyi2015** [comment]
Thanks for your suggestions. I will try to do so.

**Comment by pkuliyi2015** [comment]
Please have a try. If the error disappears, you may close the issue.

**Comment by ash0080** [comment]
> Please update and have a try. If the error disappears, you may close the issue.

Yes, It works
