### ISSUE TITLE
The upscaler generating broken result

### ISSUE THREAD

**Issue by wagnerleung0079** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#222]
I am using the latest stable-diffusion-webui-directml with an AMD Win11 PC. This happened after hours of generating. May anyone tell me what I get wrong?

![00014-1247876206](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/61477758/bb919aa9-30ae-4475-82da-5ab7b60d4b68)

**Comment by pkuliyi2015** [comment]
This is unique to AMD GPU and may not be fixed. See #93.
