### ISSUE TITLE
Tiled Diffusion, VAE, and Prompt Region Control -  non-functional in Auto1111/Vlad1111

### ISSUE THREAD

**Issue by HarrisTerry** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#225]
Trying to understand why I cannot get any results from these awesome tools.

Tilled Diffusion - no matter tile size, image size, throws out of memory error - using 3070ti 8GB

Tiled VAE - saw zero difference

Prompt Region Control - cannot make even the simplest things in the regions, they show as bright sections only

I build computers and am very good at installing things, I give SD lessons... but I must be doing something or not doing something....

Win11/ 64GB RAM / 12700k 5GHZ / 3070ti 8GB / all m.2 PCI SSD

**Comment by pkuliyi2015** [comment]
Please put your memory errors here. Normally there are three solutions you can try first.

use --xformers on startup
enable Tiled VAE, set encoder tile size to 1024, decoder to 128.
Set Latent Tile Batch Size in Tiled Diffusion to 1

**Comment by HarrisTerry** [comment]
the last two options worked, thank you! I haven't used xformers in a while since I have bene using Vlad1111 but the other tricks helped, thanks!

**Comment by pkuliyi2015** [comment]
You are welcome. Note that sdp optimizations may also lead to OOM. When you see something like sub_quadratic_product in OOM errors you may try xformers.
