### ISSUE TITLE
Black output

### ISSUE THREAD

**Issue by DigiVore-Programing** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#227]
Blackoutput with anything other than the default SafeTensors. I have done some research and found this may be an issue with the controlnet version -- fixed 4 days ago.

**Comment by DigiVore-Programing** [comment]
Did further testing and discovered it is indeed coming from this extension, I disabled it and found that it fixed the issue (while removing the nice features)

**Comment by Kahsolt** [comment]
Any further updates on this thread?
If so, more screenshot & error log please.
