### ISSUE TITLE
upscale fails halfway

### ISSUE THREAD

**Issue by JIESSS** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#23]
![xyz_grid-0002-2007259850](https://user-images.githubusercontent.com/68331733/224532278-7b323372-a23d-4564-94e3-de88ce952c97.png)

**Comment by pkuliyi2015** [comment]
Hello, the black images that usually from VAE NaNs are normal problems we have described in README. 

In general, the officially trained VAEs are not good at decoding very large images and can usually fail when upscaling. So you may encounter this regardless of tiling or not. For example, if you do highres.fix on many images, you will also meet similar problems where some results are black.

I have tried my best in solving this but cannot handle all cases. In general you need to try --no-half-vae option.

**Comment by JIESSS** [comment]
I don't know much about these, thank you for your explanation.
