### ISSUE TITLE
raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'LatentDiffusion' object has no attribute 'apply_model_original_md'

### ISSUE THREAD

**Issue by lost9999** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#235]

**Comment by pkuliyi2015** [comment]
Normally, the problem can be fixed if you restart the webui.

**Comment by mctb32** [comment]
I have the same problem, and restarting the webui does not help. The problem happens when I check "Enable Noise Inversion". When noise inversion is disabled, everything works fine. Any ideas how to fix it?

**Comment by mctb32** [comment]
The problem went away today. Not sure if a1111 updated, but I also updated a few extensions, so perhaps it was a conflict with one of them.

**Comment by n0kovo** [comment]
For anyone having this problem, disabling Dynamic Thresholding (CFG Scale Fix) solved it for me.
