### ISSUE TITLE
UnboundLocalError: local variable 'image_cond' referenced before assignment

### ISSUE THREAD

**Issue by momognu** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#236]
UnboundLocalError: local variable 'image_cond' referenced before assignment

Time taken: 0.37s

Torch active/reserved: 6039/6486 MiB, Sys VRAM: 7432/12020 MiB (61.83%)

**Comment by pkuliyi2015** [comment]
Please try to update the extension to the latest version.
If the error still exists, please provide more detailed error logs.

**Comment by pkuliyi2015** [comment]
As no more logs are provided, I will close this issue. If the problem still exists please reopen.
