### ISSUE TITLE
bboxHint performs large number of dom queries and causes large browser load

### ISSUE THREAD

**Issue by vladmandic** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#247]
in https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/blob/b28c03b10f45d44d09b570b20fe8a4f61061b294/javascript/bboxHint.js#L515-L527

even listener is attached unconditionally and causes a large number of dom queries
it even throws a warning in chrome:

```log
[Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
```

and chrome suggestion is more than valid - extension should create a mutation observer so it only observes the events when its actually visible.

**Comment by pkuliyi2015** [comment]
I can't optimize the code now, as I don't have older gradio versions for a test. 
However, I add a version checker so that this code segment will only work for gradio >3.16.0 and < 3.29.0. Any older or newer version won't get affected. I think this should be enough!
