### ISSUE TITLE
If 'keep input image size' not checked and 'scale factor' non integer, size can be non-integer, causes downstream crash.

### ISSUE THREAD

**Issue by chrisgoringe** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#248]
If scale factor isn't an integer and `Keep input image size` is not checked, the size can end up being a float, which then causes a crash.

I believe the problem is in `tileddiffusion.py` at lines 298-300:

```python
            elif upscaler.name != "None":
                p.width  = scale_factor * p.width_original_md
                p.height = scale_factor * p.height_original_md
```

Suggest that 

```python
            elif upscaler.name != "None":
                p.width  = int(scale_factor * p.width_original_md)
                p.height = int(scale_factor * p.height_original_md)
```

would fix this.

**Comment by Kahsolt** [comment]
Thx for the help, code updated as your suggestion :)

**Comment by ramyma** [comment]
It would be better to round down to the nearest multiple of 8, following the fix applied to the upscale implementation on the A1111 release candidate branch:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/3b11f17a374520e493e120e7f47443acd97393c8/modules/upscaler.py#L56
