### ISSUE TITLE
最近更新以后出图变得很慢很慢了，有同学跟我一样的吗

### ISSUE THREAD

**Issue by anselgeorge** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#250]
最近更新以后出图变得很慢很慢了，有同学跟我一样的吗

**Comment by josh5671** [comment]
rollback your nvidia driver back to 531.xx.
Nvidia changed their driver to make their 4000 series with low vram (under 10gb) fit well in latest game.
So they decide to make it unload the vram into system memory if it run out vram.
