### ISSUE TITLE
Change default parameters

### ISSUE THREAD

**Issue by Zullian** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#258]
Hello, is there any way to change default parameters?

I've tried changing ...\extensions\multidiffusion-upscaler-for-automatic1111\scriptstilediffusion.py, but it ignores it and values are default as originally.

**Comment by bobpuffer1** [comment]
I changed all my default settings, including multi diffusion by setting all my settings, and then going into settings, defaults and saving them. All my multi diffusion settings were saved in there so the next time I loaded the UI, it set my defaults to what I had set up prior to saving. I did.
