### ISSUE TITLE
visible tiles 

### ISSUE THREAD

**Issue by isek554** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#263]
![awdawdawdawd](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/0cd59bc0-0eda-4919-8f1f-98a28b7a9ad4)
![awdawdawdawdawdawd](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/88986f4e-592b-48c4-a6b1-6c2f962f3d73)
 when i upscale the tiles are being visible what's the cause anyway i can fix it ?

**Comment by isek554** [comment]
this was when i was using tiled vae.
what am i doing wrong ?
![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/665c290f-de1a-4a8c-b961-7715191c8e76)

**Comment by pkuliyi2015** [comment]
Can you provide the detailed settings that output these images?

**Comment by isek554** [comment]
![Screenshot 2023-07-02 150612](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/08c5e10b-83ed-4fd7-beee-f0163f559f99)
![Screenshot 2023-07-02 150620](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets
![Screenshot 2023-07-02 150628](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/1b844498-506c-4054-89c2-18fe24a57367)
/138154166/76ddb274-e191-4e2f-b934-8b9b40c7194c)

**Comment by isek554** [comment]
![Screenshot 2023-07-02 150628](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/c5b45138-690f-4d53-8082-774cbc877d83)

**Comment by pkuliyi2015** [comment]
try to use Mixture of diffusers method

**Comment by isek554** [comment]
i can still see some deforms when using the following settings.
![Screenshot 2023-07-02 183547](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/13815
![Screenshot 2023-07-02 183553](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/3175d2d4-fe62-4056-bb91-a280771452f5)
4166/9e0f9ae6-bfb1-40b0-81a0-588f86614b6d)
![Screenshot 2023-07-02 183557](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/36af41a8-a661-4d94-ad85-1cb4e825b7b3)

**Comment by isek554** [comment]
![Screenshot 2023-07-02 183553](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/db56f178-e54b-4eb2-9408-d7d6ed966f49)
![00102-259244359](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/a685238b-d447-473a-904c-74ed8c5fa7ac)

the original picture

**Comment by isek554** [comment]
upscaled at 2.5 denoise 

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/fc8180f8-6939-4180-8660-6c66fb68d529)
![00011-1030269906](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/ca4c7c45-874c-443e-aeb9-6051938afb6e)

**Comment by pkuliyi2015** [comment]
This seems to be quite hard to avoid. Have you used controlnet tile model?

**Comment by isek554** [comment]
i will give it a try now, any ideas what could be the cause ?

**Comment by isek554** [comment]
![00013-1284613608](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/138154166/a110ed13-becf-49a9-8540-77c1ffb87f96)
and sadly this is when i was using control net

**Comment by pkuliyi2015** [comment]
This is because the discrepancies between tiles are too large to be smoothed by tile overlap. ControlNet Tile is a way to mitigate this but it seems that it is still not enough. You may try to low the CFG to 2 or 3 to further mitigate the discrepancies.

**Comment by isek554** [comment]
lowering the cfg worked and setting tile overlapping to 62 worked too thanks for helping

**Comment by pkuliyi2015** [comment]
You are welcome.
