### ISSUE TITLE
multidiffusion is not working

### ISSUE THREAD

**Issue by liao023194** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#268]
The high resolution of multidiffusion+Tiled VAE img2img was not working well, and the generated image is still the original size.  I don't know if there is a solution. There are too many errors displayed , I don't know which one specifically affected them. I would like to ask if there are any similar issues or solutions.

multidiffusion +Tiled VAE img2img出高分辨率不好用了，生成的还是原尺寸。我问了下，有很多人也是这样。不知道有没有解决办法。后台显示报错太多了，都不知道是哪个具体影响的。想问问有没有同样问题的，或者有没有解决方案。

主要的报错的内容（还有非常多其他的报错信息）：↓
The main error content (and a lot of other error messages): ↓

*** Error running postprocess_batch: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'

**Comment by liao023194** [comment]
2023-07-11 05:21:23,645 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper
        raise error from None
    ValueError: 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.4.0                                                │ │
    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8              │ │
    │ │ Commandline │ ['D:\\AI\\Stable                                      │ │
    │ │             │ Diffusion\\sd-webui-aki-v4.1\\launch.py', '--theme',  │ │
    │ │             │ 'dark', '--xformers', '--api', '--autolaunch']        │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ (masterpiece:1.2),(best quality:1.2),(official    │ │
    │ │                 │ art:1.2),extremely detailed CG unity 8k           │ │
    │ │                 │ wallpaper,HDR,UHD,8K,masterpiece,best             │ │
    │ │                 │ quality,1girl,water blue hair,(golden             │ │
    │ │                 │ pupils:1.2),sweet girl,standing,look  at          │ │
    │ │                 │ viewer,angelic smile,waving,hair                  │ │
    │ │                 │ ornament,pendant,comic strokes,(white             │ │
    │ │                 │ background:1.3),(simple                           │ │
    │ │                 │ background:1.2),ponytail,(full body:1.1),(golden  │ │
    │ │                 │ eyes:1.1),summer  dress, pointy  footwear         │ │
    │ │ negative_prompt │ sketches,(worst quality:2),(low                   │ │
    │ │                 │ quality:2),(normal quality:2),lowres,normal       │ │
    │ │                 │ quality,                                          │ │
    │ │                 │ ((monochrome)),((grayscale)),(((skin              │ │
    │ │                 │ spots))),acnes,skin blemishes,bad anatomy,(long   │ │
    │ │                 │ hair:1.4),                                        │ │
    │ │                 │ DeepNegative,(fat:1.2),facing away,looking        │ │
    │ │                 │ away,tilted head,{Multiple people},               │ │
    │ │                 │ lowres,bad anatomy,bad hands,text,error,missing   │ │
    │ │                 │ fingers,extra digit,fewer digits,cropped,         │ │
    │ │                 │ worstquality,low quality,normal                   │ │
    │ │                 │ quality,jpegartifacts,signature,watermark,        │ │
    │ │                 │ username,blurry,bad feet,cropped,(poorly drawn    │ │
    │ │                 │ hands:2),poorly drawn face,                       │ │
    │ │                 │ mutation,deformed,worst quality,low               │ │
    │ │                 │ quality,normal quality,jpeg artifacts,            │ │
    │ │                 │ signature,watermark,(extra fingers:2),fewer       │ │
    │ │                 │ digits,extra limbs,extra arms,extra legs,         │ │
    │ │                 │ malformed limbs,fused fingers,too many            │ │
    │ │                 │ fingers,long neck,cross-eyed,mutated hands,       │ │
    │ │                 │ Polar lowres,bad body,bad proportions,gross       │ │
    │ │                 │ proportions,text,error,missing fingers,           │ │
    │ │                 │ Missing arms,missing legs,extra digit,extra       │ │
    │ │                 │ arms,extra leg,extra foot,                        │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 1024                                              │ │
    │ │          height │ 1536                                              │ │
    │ │    sampler_name │ DPM++ 2M Karras                                   │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ ouka_star.safetensors [97cddf7d1b]                │ │
    │ │             vae │ animevae.pt                                       │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ D:\AI\Stable                                                        │ │
    │ │ Diffusion\sd-webui-aki-v4.1\extensions\adetailer\adetailer\tracebac │ │
    │ │ k.py:136 in wrapper                                                 │ │
    │ │                                                                     │ │
    │ │   133 │   │   width = width - 4 if width > 4 else None              │ │
    │ │   134 │   │   console = Console(file=string, force_terminal=force_t │ │
    │ │   135 │   │   try:                                                  │ │
    │ │ > 136 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   137 │   │   except Exception as e:                                │ │
    │ │   138 │   │   │   tables = [                                        │ │
    │ │   139 │   │   │   │   get_table(title, data)                        │ │
    │ │                                                                     │ │
    │ │ D:\AI\Stable                                                        │ │
    │ │ Diffusion\sd-webui-aki-v4.1\extensions\adetailer\scripts\!adetailer │ │
    │ │ .py:500 in process                                                  │ │
    │ │                                                                     │ │
    │ │   497 │   │   if getattr(p, "_disable_adetailer", False):           │ │
    │ │   498 │   │   │   return                                            │ │
    │ │   499 │   │                                                         │ │
    │ │ > 500 │   │   if self.is_ad_enabled(*args_):                        │ │
    │ │   501 │   │   │   arg_list = self.get_args(p, *args_)               │ │
    │ │   502 │   │   │   extra_params = self.extra_params(arg_list)        │ │
    │ │   503 │   │   │   p.extra_generation_params.update(extra_params)    │ │
    │ │                                                                     │ │
    │ │ D:\AI\Stable                                                        │ │
    │ │ Diffusion\sd-webui-aki-v4.1\extensions\adetailer\scripts\!adetailer │ │
    │ │ .py:171 in is_ad_enabled                                            │ │
    │ │                                                                     │ │
    │ │   168 │   │   │   │   │      [-] ADetailer: Invalid arguments passe │ │
    │ │   169 │   │   │   │   │   │      input: {args_!r}                   │ │
    │ │   170 │   │   │   │   │      """                                    │ │
    │ │ > 171 │   │   │   raise ValueError(dedent(message))                 │ │
    │ │   172 │   │   enable = args_[0] if isinstance(args_[0], bool) else  │ │
    │ │   173 │   │   checker = EnableChecker(enable=enable, arg_list=arg_l │ │
    │ │   174 │   │   return checker.is_enabled()                           │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ ValueError:                                                             │
    │ [-] ADetailer: Invalid arguments passed to ADetailer.                   │
    │     input: ()                                                           │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

---
*** Error running process: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\sam.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\sam.py", line 785, in process
        process_unit = SAMProcessUnit(args, is_img2img)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\process_params.py", line 63, in __init__
        self.sam_inpaint_unit = SAMInpaintUnit(args, is_img2img)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\process_params.py", line 25, in __init__
        self.init_sam_single_image_process(args)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\process_params.py", line 29, in init_sam_single_image_process
        self.inpaint_upload_enable      = args[0]
    IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-cutoff\scripts\cutoff.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 8 required positional arguments: 'enabled', 'targets_', 'weight', 'disable_neg', 'strong', 'padding', 'intp', and 'debug'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-llul\scripts\llul.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-11 05:21:23,785 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process_batch: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 190, in process_batch
        if not args[0]:
    IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_batch: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_image: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper
        raise error from None
    ValueError: 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.4.0                                                │ │
    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8              │ │
    │ │ Commandline │ ['D:\\AI\\Stable                                      │ │
    │ │             │ Diffusion\\sd-webui-aki-v4.1\\launch.py', '--theme',  │ │
    │ │             │ 'dark', '--xformers', '--api', '--autolaunch']        │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ (masterpiece:1.2),(best quality:1.2),(official    │ │
    │ │                 │ art:1.2),extremely detailed CG unity 8k           │ │
    │ │                 │ wallpaper,HDR,UHD,8K,masterpiece,best             │ │
    │ │                 │ quality,1girl,water blue hair,(golden             │ │
    │ │                 │ pupils:1.2),sweet girl,standing,look  at          │ │
    │ │                 │ viewer,angelic smile,waving,hair                  │ │
    │ │                 │ ornament,pendant,comic strokes,(white             │ │
    │ │                 │ background:1.3),(simple                           │ │
    │ │                 │ background:1.2),ponytail,(full body:1.1),(golden  │ │
    │ │                 │ eyes:1.1),summer  dress, pointy  footwear         │ │
    │ │ negative_prompt │ sketches,(worst quality:2),(low                   │ │
    │ │                 │ quality:2),(normal quality:2),lowres,normal       │ │
    │ │                 │ quality,                                          │ │
    │ │                 │ ((monochrome)),((grayscale)),(((skin              │ │
    │ │                 │ spots))),acnes,skin blemishes,bad anatomy,(long   │ │
    │ │                 │ hair:1.4),                                        │ │
    │ │                 │ DeepNegative,(fat:1.2),facing away,looking        │ │
    │ │                 │ away,tilted head,{Multiple people},               │ │
    │ │                 │ lowres,bad anatomy,bad hands,text,error,missing   │ │
    │ │                 │ fingers,extra digit,fewer digits,cropped,         │ │
    │ │                 │ worstquality,low quality,normal                   │ │
    │ │                 │ quality,jpegartifacts,signature,watermark,        │ │
    │ │                 │ username,blurry,bad feet,cropped,(poorly drawn    │ │
    │ │                 │ hands:2),poorly drawn face,                       │ │
    │ │                 │ mutation,deformed,worst quality,low               │ │
    │ │                 │ quality,normal quality,jpeg artifacts,            │ │
    │ │                 │ signature,watermark,(extra fingers:2),fewer       │ │
    │ │                 │ digits,extra limbs,extra arms,extra legs,         │ │
    │ │                 │ malformed limbs,fused fingers,too many            │ │
    │ │                 │ fingers,long neck,cross-eyed,mutated hands,       │ │
    │ │                 │ Polar lowres,bad body,bad proportions,gross       │ │
    │ │                 │ proportions,text,error,missing fingers,           │ │
    │ │                 │ Missing arms,missing legs,extra digit,extra       │ │
    │ │                 │ arms,extra leg,extra foot,                        │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 1024                                              │ │
    │ │          height │ 1536                                              │ │
    │ │    sampler_name │ DPM++ 2M Karras                                   │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ ouka_star.safetensors [97cddf7d1b]                │ │
    │ │             vae │ animevae.pt                                       │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ D:\AI\Stable                                                        │ │
    │ │ Diffusion\sd-webui-aki-v4.1\extensions\adetailer\adetailer\tracebac │ │
    │ │ k.py:136 in wrapper                                                 │ │
    │ │                                                                     │ │
    │ │   133 │   │   width = width - 4 if width > 4 else None              │ │
    │ │   134 │   │   console = Console(file=string, force_terminal=force_t │ │
    │ │   135 │   │   try:                                                  │ │
    │ │ > 136 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   137 │   │   except Exception as e:                                │ │
    │ │   138 │   │   │   tables = [                                        │ │
    │ │   139 │   │   │   │   get_table(title, data)                        │ │
    │ │                                                                     │ │
    │ │ D:\AI\Stable                                                        │ │
    │ │ Diffusion\sd-webui-aki-v4.1\extensions\adetailer\scripts\!adetailer │ │
    │ │ .py:596 in postprocess_image                                        │ │
    │ │                                                                     │ │
    │ │   593 │   │   if getattr(p, "_disable_adetailer", False):           │ │
    │ │   594 │   │   │   return                                            │ │
    │ │   595 │   │                                                         │ │
    │ │ > 596 │   │   if not self.is_ad_enabled(*args_):                    │ │
    │ │   597 │   │   │   return                                            │ │
    │ │   598 │   │                                                         │ │
    │ │   599 │   │   p._ad_idx = getattr(p, "_ad_idx", -1) + 1             │ │
    │ │                                                                     │ │
    │ │ D:\AI\Stable                                                        │ │
    │ │ Diffusion\sd-webui-aki-v4.1\extensions\adetailer\scripts\!adetailer │ │
    │ │ .py:171 in is_ad_enabled                                            │ │
    │ │                                                                     │ │
    │ │   168 │   │   │   │   │      [-] ADetailer: Invalid arguments passe │ │
    │ │   169 │   │   │   │   │   │      input: {args_!r}                   │ │
    │ │   170 │   │   │   │   │      """                                    │ │
    │ │ > 171 │   │   │   raise ValueError(dedent(message))                 │ │
    │ │   172 │   │   enable = args_[0] if isinstance(args_[0], bool) else  │ │
    │ │   173 │   │   checker = EnableChecker(enable=enable, arg_list=arg_l │ │
    │ │   174 │   │   return checker.is_enabled()                           │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ ValueError:                                                             │
    │ [-] ADetailer: Invalid arguments passed to ADetailer.                   │
    │     input: ()                                                           │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

---
*** Error running postprocess: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: D:\AI\Stable Diffusion\sd-webui-aki-v4.1\extensions\sd-webui-llul\scripts\llul.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion\sd-webui-aki-v4.1\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---

**Comment by avan06** [comment]
Refer to this issue for discussion: [[Bug]: extensions errors in 1.4.0 version #11448](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448#issue-1776316105)

**Comment by soughtquinee** [comment]
请问有找到解决办法吗，我最近也老是报错，一看出图也没有放大，全部删干净重新下也是一样。会不会是1.5.1版本的不适配

**Comment by soughtquinee** [comment]
> 请问有找到解决办法吗，我最近也老是报错，一看出图也没有放大，全部删干净重新下也是一样。会不会是1.5.1版本的不适配

解决了，如上方指向的链接里所说，拓展设置里禁用掉mov2mov拓展就恢复正常了
