### ISSUE TITLE
fast encode/decode tiledVAE cause black spots

### ISSUE THREAD

**Issue by Rkkss** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#276]
It happens in newest update. 
This is done with i2i with 0 denoise strength just to make sure it isn't caused by other extensions

https://imgsli.com/MTkzNTc5

**Comment by Kahsolt** [comment]
The `Fast` mode is implemented using our approximation algorithm.
For your concrete case, the black spots appears in those over-bright places, and this is a known issue: 

** VAE numerical overflow, for those high color contrast images. **

The best work around is to set your VAE working in F32 precision, by adding command line args `--no-half-vae`.
The other way is to re-scale value range when overflow occurs, but this requires more detecting code and cause performance degradation, so we did not implement it :)
