### ISSUE TITLE
Missing "Upscaler interface"?

### ISSUE THREAD

**Issue by matichek** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#28]
Hello, I can not find the "upscaler slider" and sampler selection. 

Pink one in the picture is Chinese version. 

Blue one is my latest one. 

Please take a look - maybe I am selecting something wrong? 

![missing](https://user-images.githubusercontent.com/3986047/224750871-0ff5d003-9642-4c6e-93f5-1a55a8c12811.jpg)

**Comment by matichek** [comment]
Ah, sorry, the selector is only in img2img.

**Comment by andupotorac** [comment]
> 

So we should use the selector in img2img even if we use text2image mode? Should we also enable img2img checkbox for it so that in text2image it takes it from there??
