### ISSUE TITLE
Question:possible to make this project portable?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#280]
from your experience. do you think is it possible to make this project itself into a separate gradio app?

so we can>python app.py

just curious because I want to make it into a seperate app(not for commercial ^^).

**Comment by Kahsolt** [comment]
Nope, this extension works on sd-webui's application abstract layers.
If you port an extension, you bundle up the entire sd-webui.
