### ISSUE TITLE
Interrupt generation creating wrong images with Tiled VAE enabled

### ISSUE THREAD

**Issue by dhwz** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#286]
Something is not working properly if you interrupt generation then the image getting not decoded properly with Tiled VAE enabled.
Can you please check if you can fix that?

Tiled VAE disabled:
![1](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3697946/f03557a0-39d3-42ee-bfd4-3de7b2e5b2b2)

Tiled VAE enabled:
![2](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/3697946/957a5df7-e928-430d-aeb2-5d61f941b632)

**Comment by Kahsolt** [comment]
This is a feature, NOT bug.
When tiled-vae is interrupted, no output will be given (it is NOT the same case when interrupt the UNet).

However, this behaviour is unfriendly.
So I give it a fallback, in this case you will get a `vae-cheap-approx` decoded image. (Right as the image you post)
This fallback is at nearly zero resource cost, so I chose it.

Remember this: if you really determined to stop vae decoding, you are NOT expected to get any meaningful result.
I show this `vae-cheap-approx` decoded image, only for your reference of what has been done in UNet, mostly for debug sense.
