### ISSUE TITLE
How to control the use of multidiffusion through an API? 

### ISSUE THREAD

**Issue by gaibohan** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#287]
I am using C# programming and generating images through Text2Image. The JSON fragment I am sending is: However, there is no region information([Tiled Diffusion] ignore tiling when there's only 1 tile or nothing to do :)), how can I modify it to control image generation through the API? Thank you very much, everyone!
{
    "init_images":[

    ],
    "denoising_strength":0.75,
    "inpainting_fill":1,
    "prompt":"",
    "seed":-1,
    "batch_size":1,
    "n_iter":1,
    "steps":50,
    "cfg_scale":7,
    "width":512,
    "height":512,
    "negative_prompt":"",
    "sampler_index":"Euler",
    "alwayson_scripts":{
        "controlNet":{
            "args":[
                {
                    "enabled":false,
                    "input_image":"",
                    "mask":null,
                    "module":"",
                    "preprocessor":null,
                    "resize_mode":"Just Resize",
                    "model":"control_v11f1e_sd15_tile [a371b31b]",
                    "weight":1,
                    "processor_res":64,
                    "guidance_start":0,
                    "guidance_end":1,
                    "control_mode":"Balanced",
                    "pixel_perfect":true,
                    "threshold_a":1,
                    "threshold_b":64
                }
            ]
        },
        "Tiled Diffusion":{
            "args":[
                {
                    "enabled":true,
                    "Method":"MultiDiffusion",
                    "Tile tile width":96,
                    "Tile tile height":96,
                    "Tile Overlap":48,
                    "Tile batch size":4,
                    "BBox Settings":[
                        {
                            "enable":true,
                            "x":0,
                            "y":0,
                            "w":0.5,
                            "h":0.3,
                            "prompt":"a black cat",
                            "neg_prompt":"",
                            "blend_mode":"Foreground",
                            "feather_ratio":0.2,
                            "seed":-1
                        },
                        {
                            "enable":true,
                            "x":0.5,
                            "y":0,
                            "w":0.5,
                            "h":0.3,
                            "prompt":"a white cat",
                            "neg_prompt":"",
                            "blend_mode":"Foreground",
                            "feather_ratio":0.2,
                            "seed":-1
                        }
                    ]
                }
            ]
        }
    },
    "_Model_Name":null,
    "_Model_Hash":null,
    "_Version":1
}

**Comment by Kahsolt** [comment]
Your target canvas is 512x512 (in pixel size), which is actually smaller than one single tile 96x96 (in latent size).
**Note that latent is x8 smaller than the pixel.**
Hence for this configuration, tiling is not necessary and ignored.

Obviously tiled-diffusion is aimed for drawing large pictures (~2k), on low VRAM devices.
However, if your insist on testing this tiling mechanism on small canvas, you can set `tile width/height` to the minimal, and make sure your target canvas is x8 larger than it ;)
