### ISSUE TITLE
noise inversion implementation principle?

### ISSUE THREAD

**Issue by krNeko9t** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#289]
The noise inversion helps a lot with upscale structure preserve, but i can't understand how it is implemented while reading the code, for i want to use noise inversion in some diffusers-based project. Can you please give some hints or articles of how you come up this method? Thanks a lot!

**Comment by tengjiayan20** [comment]
Exciting work!
However, I am still confused about how you transfer the noise inversion above to "tiled" noise inversion for upscaling?
Thank you very much!
