### ISSUE TITLE
LoRa doesn't work in Region Propmt Control

### ISSUE THREAD

**Issue by Lemniscatas** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#293]
Emmeddings doesn't work inside Regional Prompt Control too. In main txt2img prompt they work (and Loras too).

I've tried all the settings (setted Feather from 0 to 1, writed LoRas to background - same result; with/without negatives, used different VAEs and different checkpoints).

What have I do?
How can I activate them?

**Comment by Kahsolt** [comment]
Sadly can not support this.
Region Prompt Control is very raw and experimental.
To support the whole extension scripts pipeline in RPC is killing, unless RPC becomes a part of the fundamental architecture in sd-webui, rather than being a feature within an extension.

**Comment by Lemniscatas** [comment]
Sad to hear about it. Let's hope for the introduction of new features
