### ISSUE TITLE
Tile Vae create weird chess rectangle shape on the upscale image if using SDXL

### ISSUE THREAD

**Issue by wardensc2** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#297]
I try to upscale SDXL image using Tile Vae and get this kind of weird chess rectangle shape on the image, anyone know how to fix it ?

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/77379748/2fd93e19-b82a-4ae2-af09-7240bb1b8d24)

This is my setting

![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/77379748/67cfc549-f7ee-48dd-9bd2-2081616363bf)

**Comment by WhiteZeroX** [comment]
Same for me. You have to disable Fast Encoder and Fast Decoder.

**Comment by Rkkss** [comment]
Probably related
https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/276#issuecomment-1692682361

**Comment by wardensc2** [comment]
> Probably related [#276 (comment)](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/276#issuecomment-1692682361)

> Same for me. You have to disable Fast Encoder and Fast Decoder.

I already using no half vae, disable Fast Encoder and Decoder work for me. Thanks
