### ISSUE TITLE
what different from unfold/fold in stable diffusion ?

### ISSUE THREAD

**Issue by lizhengwei1992** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#30]
when I use StableDiffusion x4 upscaler to process image with >256x256 resolution,  OOM errors happened frequently。

I divide latens into many patchs following the operation (unfold/fold) in latent-diffusion(https://github.com/CompVis/latent-diffusion/blob/main/ldm/models/diffusion/ddpm.py#L601，https://github.com/CompVis/latent-diffusion/blob/main/ldm/models/diffusion/ddpm.py#L715), this reduce memory substantially when decoding latents output,  it seems similar to this method ?

**Comment by pkuliyi2015** [comment]
Yes, they are very similar. Before I write multidiffusion I have discovered this fold & unfold in the LDSR pipeline when size>128. But basically Multidiffusion showed us that We can achieve multiple tile fusion without complex weighting and normalization. Secondly torch.unfold & fold only support regular kernel shapes and stride, so in many cases when the input size is not dividable

**Comment by lizhengwei1992** [comment]
Thanks for your explanation very much ! 
The main problem is that divided patchs lost global information in decoder module using unfold/fold operation for SD upscaler，the contrast of output super resolution image will change,  your method occurs the same problem ?

**Comment by pkuliyi2015** [comment]
I believe may not. I am not applying the same normalizing techniques as them.
