### ISSUE TITLE
Please update extension to support A1111 1.6

### ISSUE THREAD

**Issue by wardensc2** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#302]
Dear pkuliyi2015

We know you' re very busy but please support us when you have time. Please update this amazing extension to make it work in A1111 1.6 version. Right now only Tile Vae working, multi region does not work. Your Region Prompt Control is the main region we keep study SD due to its powerful divive prompt per region.

Right now if you're too busy maybe you dont need to make this extension work with SDXL yet but please make it support A1111 1.6

Thank you so much

**Comment by Duemellon** [comment]
I was wondering why I wasnt' getting anything when I launched it for the first time. I've never used it. This looks like an amazing tool!

**Comment by Kahsolt** [comment]
recent commit should let it work with A1111 v1.6 now
notify me if anything still not work, or please close the issue :)

**Comment by wardensc2** [comment]
> recent commit should let it work with A1111 v1.6 now notify me if anything still not work, or please close the issue :)

Thank you so much for your efforts.
