### ISSUE TITLE
multidiffusion插件没有正常安装

### ISSUE THREAD

**Issue by TCmatj** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#31]
如题

**Comment by pkuliyi2015** [comment]
没有看懂，请给出具体的截图

**Comment by TCmatj** [comment]
我的stable-diffusion-webui使用git clone会报old style错，，所以我就在extension文件夹下打开了git bash手动clone的仓库，但是启动以后只有vue，没有另一个插件的界面
![2023-03-15](https://user-images.githubusercontent.com/34977256/225204288-838929ba-ad82-4a27-8f4d-ef51f8f8595c.png)

**Comment by pkuliyi2015** [comment]
你可以尝试手动下载zip文件解压到那个文件夹。国内的网络是个什么情况？想必不用多言

**Comment by TCmatj** [comment]
> 你可以尝试手动下载zip文件解压到那个文件夹。国内的网络是个什么情况？想必不用多言

emmmmm已经尝试过了不行，才手动去clone试试的

**Comment by pkuliyi2015** [comment]
这个问题非常奇怪。至少我刚刚重新搭建环境，clone以后是没问题的。你的webui是最新版么？multidiffusion.py这个文件在正确的位置么？

**Comment by TCmatj** [comment]
> 这个问题非常奇怪。至少我刚刚重新搭建环境，clone以后是没问题的。你的webui是最新版么？multidiffusion.py这个文件在正确的位置么？

在的，，，不过我的sd昨晚崩溃了，修复不了，我后面再重新装一下再试试

**Comment by pkuliyi2015** [comment]
webui本身更新频繁，不太稳定，如果更新后没有问题记得关闭issue。
