### ISSUE TITLE
MultiDiffusion was suddenly unavailable today.

### ISSUE THREAD

**Issue by player99963** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#312]
Loading VAE weights specified in settings: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\VAE\orangemix.vae.pt
Applying attention optimization: sdp... done.
Model loaded in 8.1s (load weights from disk: 1.5s, create model: 0.7s, apply weights to model: 1.8s, apply channels_last: 1.7s, load VAE: 0.5s, load textual inversion embeddings: 0.3s, calculate empty prompt: 1.4s).
MultiDiffusion Sampling: : 0it [00:00, ?it/s]MultiDiffusion hooked into 'DPM++ 2M Karras' sampler, Tile size: 96x96, Tile batches: 1, Batch size: 4.
                                                                                                                       > d:\a1111 web ui autoinstaller\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py(132)repeat_cond_dict()
-> n_rep = len(bboxes)
(Pdb)

昨天使用都還很正常，今天突然就無法運行了。
MultiDiffusion才有這問題，切到Mixture of Diffusers就正常。

**Comment by gabdfreitas** [comment]
having the same issue

**Comment by wardensc2** [comment]
Roll back to the last commit, we just have a new commit that have some bugs

**Comment by Kahsolt** [comment]
别急，在改了在改了

**Comment by ivever2** [comment]
我也是报这个错误，赶紧来看看~~~~
