### ISSUE TITLE
Compatibility with SD.Next

### ISSUE THREAD

**Issue by GodEmperor785** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#318]
After recent updates it seems that this extension now doesn't work with SD.Next (fork of A1111: https://github.com/vladmandic/automatic). It used to work fine not long ago and it even was automatically included in SD.Next until recently

First there are import errors at start which prevent extension to load:
17:51:04-495876 ERROR    Module load: extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:
                         ImportError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\sd_next\modules\script_loading.py:21 in load_module                                                           │
│                                                                                                                     │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                          │
│ > 21 │   │   │   │   module_spec.loader.exec_module(module)                                                         │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                          │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:71 in <module>          │
│                                                                                                                     │
│    70                                                                                                               │
│ >  71 from tile_methods.abstractdiffusion import AbstractDiffusion                                                  │
│    72 from tile_methods.multidiffusion import MultiDiffusion                                                        │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py:13 in <module> │
│                                                                                                                     │
│    12                                                                                                               │
│ >  13 from tile_utils.utils import *                                                                                │
│    14                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py:15 in <module>               │
│                                                                                                                     │
│    14                                                                                                               │
│ >  15 from tile_utils.typing import *                                                                               │
│    16                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py:14 in <module>              │
│                                                                                                                     │
│   13 from modules.sd_samplers_kdiffusion import KDiffusionSampler, CFGDenoiser                                      │
│ > 14 from modules.sd_samplers_timesteps import CompVisSampler, CompVisTimestepsDenoiser, Comp                       │
│   15                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'CompVisSampler' from 'modules.sd_samplers_timesteps'
(H:\AI\sd_next\modules\sd_samplers_timesteps.py)
17:51:04-535609 ERROR    Module load: extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilevae.py:
                         ImportError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\sd_next\modules\script_loading.py:21 in load_module                                                           │
│                                                                                                                     │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                          │
│ > 21 │   │   │   │   module_spec.loader.exec_module(module)                                                         │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                          │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilevae.py:71 in <module>                │
│                                                                                                                     │
│    70 from tile_utils.attn import get_attn_func                                                                     │
│ >  71 from tile_utils.typing import Processing                                                                      │
│    72                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py:14 in <module>              │
│                                                                                                                     │
│   13 from modules.sd_samplers_kdiffusion import KDiffusionSampler, CFGDenoiser                                      │
│ > 14 from modules.sd_samplers_timesteps import CompVisSampler, CompVisTimestepsDenoiser, Comp                       │
│   15                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'CompVisSampler' from 'modules.sd_samplers_timesteps'
(H:\AI\sd_next\modules\sd_samplers_timesteps.py)

As a workaround I tried to remove all mentions of this missing 'CompVisSampler' and after this extension loaded without errors and showed correctly in the UI. Unfortunately when using it there were more errors (this was on simple 2x upscale in img2img with Mixture of Diffusers (MultiDiffusion fails in similar way) + region prompt control on SD 1.5 model, DPM++ 2M sampler):
18:00:56-832160 ERROR    gradio call: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\sd_next\modules\call_queue.py:34 in f                                                                         │
│                                                                                                                     │
│   33 │   │   │   try:                                                                                               │
│ > 34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│   35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                     │
│ H:\AI\sd_next\modules\img2img.py:219 in img2img                                                                     │
│                                                                                                                     │
│   218 │   │   if processed is None:                                                                                 │
│ > 219 │   │   │   processed = processing.process_images(p)                                                          │
│   220 │   p.close()                                                                                                 │
│                                                                                                                     │
│ H:\AI\sd_next\modules\processing.py:680 in process_images                                                           │
│                                                                                                                     │
│    679 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                        │
│ >  680 │   │   │   │   res = process_images_inner(p)                                                                │
│    681 │   finally:                                                                                                 │
│                                                                                                                     │
│ H:\AI\sd_next\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py:42 in processing_process_images_hijack │
│                                                                                                                     │
│    41 │   │   │   # we are not in batch mode, fallback to original function                                         │
│ >  42 │   │   │   return getattr(processing, '__controlnet_original_process_images_inner')(p,                       │
│    43                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\modules\processing.py:815 in process_images_inner                                                     │
│                                                                                                                     │
│    814 │   │   │   │   with devices.without_autocast() if devices.unet_needs_upcast else device                     │
│ >  815 │   │   │   │   │   samples_ddim = p.sample(conditioning=c, unconditional_conditioning=u                     │
│    816 │   │   │   │   x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(                     │
│                                                                                                                     │
│                                              ... 13 frames hidden ...                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py:70 in             │
│ kdiff_forward                                                                                                       │
│                                                                                                                     │
│    69 │   │                                                                                                         │
│ >  70 │   │   return self.sample_one_step(x_in, org_func, repeat_func, custom_func)                                 │
│    71                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py:187 in            │
│ sample_one_step                                                                                                     │
│                                                                                                                     │
│   186 │   │   │   │   # retrieve original x_in from construncted input                                              │
│ > 187 │   │   │   │   x_tile_out = custom_func(x_tile, bbox_id, bbox)                                               │
│   188                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py:68 in custom_func │
│                                                                                                                     │
│    67 │   │   def custom_func(x:Tensor, bbox_id:int, bbox:CustomBBox) -> Tensor:                                    │
│ >  68 │   │   │   return self.kdiff_custom_forward(x, sigma_in, cond, bbox_id, bbox, self.samp                      │
│    69                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py:246 in wrapper               │
│                                                                                                                     │
│   245 │   def wrapper(*args, **kwargs):                                                                             │
│ > 246 │   │   return fn(*args, **kwargs)                                                                            │
│   247 │   return wrapper                                                                                            │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py:265 in         │
│ kdiff_custom_forward                                                                                                │
│                                                                                                                     │
│   264 │   │                                                                                                         │
│ > 265 │   │   if self.kdiff_step != self.sampler.step:                                                              │
│   266 │   │   │   self.kdiff_step = self.sampler.step                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'KDiffusionSampler' object has no attribute 'step'

It is worth to mention that Tiled VAE (when used alone) actually worked after removing references to 'CompVisSampler' with just this error:
17:59:27-641308 ERROR    Decode simple: 'NoneType' object has no attribute 'to'
But result image was generated without problems

I also tried going back to commit before recent updates with "git checkout f9f8073e64f4e682838f255215039ba7884553bf", after this extension loaded without any problems. Also during usage (same thing as previously) there were no problems apart from the error in Tiled VAE as previously which doesn't seem to affect generation in any way. So it seems that recent commits are the cause of incompatibility.

This extension was for a long time automatically included in SD.Next but now due to errors it can't be. It would be great to have it compatible with SD.Next again. Would this be possible?

**Comment by gohan2091** [comment]
Updated SD.Next today (actually a clean install) and I am getting the same error. Anyone know how to fix this?

**Comment by Kahsolt** [comment]
@GodEmperor785 
many thanks to your detailed error report, the last two commit are fixes to each of them

recent efforts are trying to add SDXL support, most of the bugs raised in the issue list are caused by code refactoring
very sorry for bringing you any inconvenience :(

**Comment by GodEmperor785** [comment]
Thanks for looking into this quickly
I checked on newest commit https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/350dc0e3e054293aabafe7d563c3912147548e87 but unfortunately still some issues exist on SD.Next

Issue with import is now fixed and extension loads without issues, Tiled VAE works fine (with message mentioned previously "ERROR    Decode simple: 'NoneType' object has no attribute 'to'" which doesn't seem to affect result)

But when using Tiled Diffusion (both Multidiffusion and mixture of diffusers, with or without region control) there is this error before anything starts generating:
09:15:04-274141 ERROR    gradio call: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\sd_next\modules\call_queue.py:34 in f                                                                         │
│                                                                                                                     │
│   33 │   │   │   try:                                                                                               │
│ > 34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│   35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                     │
│ H:\AI\sd_next\modules\img2img.py:219 in img2img                                                                     │
│                                                                                                                     │
│   218 │   │   if processed is None:                                                                                 │
│ > 219 │   │   │   processed = processing.process_images(p)                                                          │
│   220 │   p.close()                                                                                                 │
│                                                                                                                     │
│ H:\AI\sd_next\modules\processing.py:683 in process_images                                                           │
│                                                                                                                     │
│    682 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                        │
│ >  683 │   │   │   │   res = process_images_inner(p)                                                                │
│    684 │   finally:                                                                                                 │
│                                                                                                                     │
│ H:\AI\sd_next\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py:42 in processing_process_images_hijack │
│                                                                                                                     │
│    41 │   │   │   # we are not in batch mode, fallback to original function                                         │
│ >  42 │   │   │   return getattr(processing, '__controlnet_original_process_images_inner')(p,                       │
│    43                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\modules\processing.py:774 in process_images_inner                                                     │
│                                                                                                                     │
│    773 │   │   with devices.autocast():                                                                             │
│ >  774 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                                               │
│    775 │   │   if shared.state.job_count == -1:                                                                     │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:435 in                  │
│ create_sampler_hijack                                                                                               │
│                                                                                                                     │
│   434 │   │   # delegate hacks into the `sampler` with context of `p`                                               │
│ > 435 │   │   delegate = delegate_cls(p, sampler)                                                                   │
│   436                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py:12 in __init__    │
│                                                                                                                     │
│    11 │   def __init__(self, p:Processing, *args, **kwargs):                                                        │
│ >  12 │   │   super().__init__(p, *args, **kwargs)                                                                  │
│    13 │   │   assert p.sampler_name != 'UniPC', 'MultiDiffusion is not compatible with UniPC!'                      │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py:17 in __init__ │
│                                                                                                                     │
│    16 │   │   # fix. Kdiff 'AND' support and image editing model support                                            │
│ >  17 │   │   if self.is_kdiff and not hasattr(self, 'is_edit_model'):                                              │
│    18 │   │   │   self.is_edit_model = (shared.sd_model.cond_stage_key == "edit"      # "txt"                       │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py:79 in is_kdiff │
│                                                                                                                     │
│    78 │   def is_kdiff(self):                                                                                       │
│ >  79 │   │   return isinstance(self.sampler_raw, KDiffusionSampler)                                                │
│    80                                                                                                               │
│                                                                                                                     │
│ C:\Users\user\AppData\Local\Programs\Python\Python310\lib\typing.py:396 in __instancecheck__                        │
│                                                                                                                     │
│    395 │   def __instancecheck__(self, obj):                                                                        │
│ >  396 │   │   raise TypeError(f"{self} cannot be used with isinstance()")                                          │
│    397                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: typing.Any cannot be used with isinstance()

I made a quick workaround just to check if anything will have errors later:
I changed is_kdiff to something that wouldn't throw exception just for test:
`def is_kdiff(self):
        return True`
But I guess it needs to be something smarter than this as a final solution

With this workaround generation seems to have worked fine with both multidiffusion and mixture of diffusers, with region control and without

I checked also if it works with ControlNet tile as it used to in the past (and produced great results) but unfortunately there is another error with ControlNet (preprocessor tile_resample + model tile) enabled:
09:22:12-723757 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\sd_next\modules\call_queue.py:34 in f                                                                         │
│                                                                                                                     │
│   33 │   │   │   try:                                                                                               │
│ > 34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│   35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                     │
│ H:\AI\sd_next\modules\img2img.py:219 in img2img                                                                     │
│                                                                                                                     │
│   218 │   │   if processed is None:                                                                                 │
│ > 219 │   │   │   processed = processing.process_images(p)                                                          │
│   220 │   p.close()                                                                                                 │
│                                                                                                                     │
│ H:\AI\sd_next\modules\processing.py:683 in process_images                                                           │
│                                                                                                                     │
│    682 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                        │
│ >  683 │   │   │   │   res = process_images_inner(p)                                                                │
│    684 │   finally:                                                                                                 │
│                                                                                                                     │
│ H:\AI\sd_next\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py:42 in processing_process_images_hijack │
│                                                                                                                     │
│    41 │   │   │   # we are not in batch mode, fallback to original function                                         │
│ >  42 │   │   │   return getattr(processing, '__controlnet_original_process_images_inner')(p,                       │
│    43                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\modules\processing.py:774 in process_images_inner                                                     │
│                                                                                                                     │
│    773 │   │   with devices.autocast():                                                                             │
│ >  774 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                                               │
│    775 │   │   if shared.state.job_count == -1:                                                                     │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:447 in                  │
│ create_sampler_hijack                                                                                               │
│                                                                                                                     │
│   446 │   │   if self.controlnet_script:                                                                            │
│ > 447 │   │   │   delegate.init_controlnet(self.controlnet_script, control_tensor_cpu)                              │
│   448 │   │   if self.stablesr_script:                                                                              │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py:249 in wrapper               │
│                                                                                                                     │
│   248 │   def wrapper(*args, **kwargs):                                                                             │
│ > 249 │   │   return fn(*args, **kwargs)                                                                            │
│   250 │   return wrapper                                                                                            │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py:466 in         │
│ init_controlnet                                                                                                     │
│                                                                                                                     │
│   465 │   │                                                                                                         │
│ > 466 │   │   self.prepare_controlnet_tensors()                                                                     │
│   467                                                                                                               │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py:249 in wrapper               │
│                                                                                                                     │
│   248 │   def wrapper(*args, **kwargs):                                                                             │
│ > 249 │   │   return fn(*args, **kwargs)                                                                            │
│   250 │   return wrapper                                                                                            │
│                                                                                                                     │
│ H:\AI\sd_next\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py:505 in         │
│ prepare_controlnet_tensors                                                                                          │
│                                                                                                                     │
│   504 │   │   │   │   │   single_batch_tensors.append(control_tile)                                                 │
│ > 505 │   │   │   │   control_tile = torch.cat(single_batch_tensors, dim=0)                                         │
│   506 │   │   │   │   if self.control_tensor_cpu:                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 768 but got size 384 for tensor number 2
in the list.

Note: all my tests were in img2img for upscaling a generated image, sampler was DPM++ 2M karras as previously and model was based on SD1.5

Could you check these new errors?

**Comment by Kahsolt** [comment]
ControlNet is possibly broken, after months of rolling-updates, and would take a long time to check.
@pkuliyi2015 is more familiar with that part of code :(, but when will the king return...

**Comment by Kahsolt** [comment]
Many thanks for your patient & detailed bug tracing :)
