### ISSUE TITLE
Invalidly says "[Tiled VAE]: the input size is tiny and unnecessary to tile."

### ISSUE THREAD

**Issue by BlankFX1** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#329]
I recently realized that no matter what I'm doing, Tiled VAE will always tell me this.
It doesn't make a difference if I set the Encoder Tile Size to 256, 1024 or 3072 or the images input size to 512, 1024 or 1536.
It also seems to make no difference if I'm using a SD1.5- or SDXL-Model.

Right now I'm trying to use SDXL for an 1536x1536-Image and it's filling my 24 GB VRAM I tried to use Tile VAE.
So as I would like to set the Encode Tile Size to 1024, but it'll just claim 1536 is smaller than 1024.
It's also claiming that 1536 is smaller than 256.

**Comment by pkuliyi2015** [comment]
The encoder only works for img2img, and the decoder tile size should be multiplied by 8, i.e. decoder 256 == image 2048.

**Comment by BlankFX1** [comment]
Thanks for the Info regarding the encoder. 
I just wanted to retest to see that the default decoder is already at 192 which multiplied by 8 is already exactly my target 1536x1536.

Yet, I'm getting `[Tiled VAE]: the input size is tiny and unnecessary to tile.`

Same situation for decoder 256  == image 2048.

Also did a test where I disabled every other Extension I have installed so only this one remains active, yet it's giving me this error and keeps overloading my VRAM.

**Comment by pkuliyi2015** [comment]
> Thanks for the Info regarding the encoder. I just wanted to retest to see that the default decoder is already at 192 which multiplied by 8 is already exactly my target 1536x1536.
> 
> Yet, I'm getting `[Tiled VAE]: the input size is tiny and unnecessary to tile.`
> 
> Same situation for decoder 256 == image 2048.
> 
> Also did a test where I disabled every other Extension I have installed so only this one remains active, yet it's giving me this error and keeps overloading my VRAM.

Only when your image is larger than that number will TileVAE split your image into tiles. You can try decoder sizes = 64 which means 512 image size. In such a case, the VRAM consumption should be no more than generating a 512 * 512 image.
