### ISSUE TITLE
Tile vae does not run normally on Apple m1 chip

### ISSUE THREAD

**Issue by NextDoorLaoHuang-HF** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#33]
multidiffusion works normally, but when tile vae is turned on, an error is reported:
Input type (float) and bias type (c10::Half) should be the same

**Comment by pkuliyi2015** [comment]
Please try the dev branch. I developed some features there but need testing. If that solves your problem please tell me, I'm willing to merge it into the main branch.

**Comment by pkuliyi2015** [comment]
Thanks for the feedback I may need a friend who have Mac to do such kind of debugging

**Comment by NextDoorLaoHuang-HF** [comment]
Thank you for your reply, which successfully solved one of my puzzles

**Comment by pkuliyi2015** [comment]
You are welcome. I also got a deeper understand to Mac chips.

**Comment by rovo79** [comment]
I had been running into this error today. Tried lots of adjustments on my Mac M1. Found my way here to discover I just needed to disabled Tiled VAE.
