### ISSUE TITLE
8G 显存 各项参数设置多少会比较能得到一个理想的结果？

### ISSUE THREAD

**Issue by Myoko** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#34]
显卡 显存比较小只有8G 不知道各项参数设置在多少范围内 能比较能得到一个理想的结果？好像没有看到有相关的介绍这个插件的视频或者教程！现在使用不知道该怎么设置！

**Comment by pkuliyi2015** [comment]
8G不小了。简介视频确实是没时间做，我在做区域prompt控制的控件

**Comment by Myoko** [comment]
> 
那就是基本上保持默认不用改就可以了吧？昨天试了几张不太理想，好像VAE前面哪一项调大了容易爆显存

**Comment by pkuliyi2015** [comment]
是的。调大肯定容易爆，而且小尺寸和大尺寸速度差不太多。所以只要爆显存你就调小就行（推荐encoder最小不小于512).  另外如果出图清晰度受到影响可以开颜色修正，开了以后和原本的没有肉眼上的区别。

**Comment by Myoko** [comment]
> 是的。调大肯定容易爆，而且小尺寸和大尺寸速度差不太多。所以只要爆显存你就调小就行（推荐encoder最小不小于512). 另外如果出图清晰度受到影响可以开颜色修正，开了以后和原本的没有肉眼上的区别。如果问题解决记得关闭issue！

用tex2image 为什么出来的图是这样的
![未命名](https://user-images.githubusercontent.com/3013386/225539123-98903f85-6599-452d-812c-ecaafeac08a7.png)
用的默认设置
![未命名2](https://user-images.githubusercontent.com/3013386/225539239-57043cca-33f1-4caf-b948-e9014b76331f.png)

**Comment by pkuliyi2015** [comment]
txt2img暂时不能出裸图，原因是现阶段他会把同一个prompt用到所有的子区域上。你需要等我写好区域prompt控制，目前UI已经搞得差不多了

**Comment by Myoko** [comment]
> txt2img暂时不能出裸图，原因是现阶段他会把同一个prompt用到所有的子区域上。你需要等我写好区域prompt控制，目前UI已经搞得差不多了

非裸图也不行！文生图出的全是这样
![00000-1221807109](https://user-images.githubusercontent.com/3013386/225543467-e6753ce4-b56d-41f4-86cd-5b3da7d2ee60.png)
