### ISSUE TITLE
is decoder_tile_size the size on latent code or size on image?

### ISSUE THREAD

**Issue by Luciennnnnnn** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#344]
Hi, is decoder_tile_size the size on latent? So are we upscale a `decoder_tile_size * decoder_tile_size` latent code tile into `decoder_tile_size * vae_scale` image tile?

**Comment by Kahsolt** [comment]
Yes, `decoder_tile_size` is the latent size :)
we use this number rather than pixel space size, because it indicates VRAM usage more directly, which we all concern
