### ISSUE TITLE
DemoFusion broke Config-Presets

### ISSUE THREAD

**Issue by AllInOneMighty** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#357]
The button ID of Tiled Diffusion and DemoFusion are the same, which means [Config-Presets](https://github.com/Zyin055/Config-Presets) cannot load them correctly anymore.

Tiled Diffusion:
![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/1002605/52bc2093-389e-4b85-a6bd-dba407ba1d1d)

DemoFusion:
![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/1002605/8f2550e6-3054-428b-a800-540ea1bbe650)

Config-Presets allows to set extension fields by identifying them by ID, but it does not work anymore because it tries to update the wrong field. Also, in HTML, two fields should not have the same ID regardless.

Is it possible to fix?

**Comment by AllInOneMighty** [comment]
```
    def ui(self, is_img2img):
        ext_id = 'demofusion'
        tab    = f'{ext_id}-t2i'  if not is_img2img else f'{ext_id}-i2i'
        is_t2i = 'true' if not is_img2img else 'false'
        uid = lambda name: f'MD-{tab}-{name}'
        # Rest of the code
```

**Comment by Jaylen-Lee** [comment]
Thank you for your suggestion. The beginner who submitted code for the first time has already made the necessary modifications. ૮(˶ᵔ ᵕ ᵔ˶)ა

**Comment by AllInOneMighty** [comment]
Thank you so much!
