### ISSUE TITLE
Error after generating image

### ISSUE THREAD

**Issue by heftig** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#372]
Since the latest update (#371) I get an error in the terminal after generating an image (with MultiDiffusion and DemoFusion disabled):

```
*** Error running postprocess_batch_list: C:\Users\janst\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py[00:03<00:00, 20.53it/s]
    Traceback (most recent call last):
      File "C:\Users\janst\AI\stable-diffusion-webui\modules\scripts.py", line 868, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Users\janst\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py", line 227, in postprocess_batch_list
        pp.images[idx] = image[:,:image.shape[1]//(p.scale_factor)*(idx_b+1),:image.shape[2]//(p.scale_factor)*(idx_b+1)]
                                                   ^^^^^^^^^^^^^^
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'scale_factor'
```

**Comment by swumagic** [comment]
me too

**Comment by CH-ZH** [comment]
Same here.

**Comment by Sesame7** [comment]
Same, here.
Stable Diffusion WebUI works everything fine on my laptop till yesterday. After I updated some plugins today, this error message appears on my laptop.

**Comment by BannyLon** [comment]
It seems like after the upgrade

**Comment by CalladsEssence** [comment]
Disclaimer: very crude solution!
This will probably break something else if MultiDiffusion and/or DemoFusion are enabled, so use at own risk :) 

Browse to: stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts

** Now FIRST make a copy of tileglobal.py and store it outside the folder. (if you keep it in the same folder, it will still be read and produce the same error). **

Now open the original file tileglobal.py in notepad++ and remove a complete section starting at line 224 to 237. (so 14 lines are removed). Save the file and re-start the server. (So close A1111 completely and start it up again).

Should work for normal txt2img with hires fix and img2img also.
If you find something else broken by this solution, simply restore the file you have copied.

**Comment by HyperTwo** [comment]
the same problem

**Comment by yanxbo2022** [comment]
我也一样，等修复了！

**Comment by TheSummerRain** [comment]
我也是

**Comment by Jaylen-Lee** [comment]
just update to latest version， and this bug has been fixed
