### ISSUE TITLE
考虑做一下comfyUI的node吗？

### ISSUE THREAD

**Issue by sh570655308** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#39]
因为放大的时候对prompt有限制，而对于comfyUI来说放大的prompt本来就是单独设置的，应该会非常契合。

**Comment by pkuliyi2015** [comment]
我看了一下他们的代码，暂时没有兴趣。我主要是为了验证技术猜想写的这个，并不是真的要搞生产，哈哈

**Comment by Kahsolt** [comment]
try use this [https://github.com/BlenderNeko/ComfyUI_TiledKSampler](https://github.com/BlenderNeko/ComfyUI_TiledKSampler)
