### ISSUE TITLE
Please make the extension off by default

### ISSUE THREAD

**Issue by NoCrypt** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#4]
Nothing fancy, I guess making the extension off by default is much more common
https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/blob/main/scripts/vae_optimize.py#L111

**Comment by pkuliyi2015** [comment]
Oh I remembered to do so but finally forgot...Thank you for reminding me.
