### ISSUE TITLE
Error using inpainting with multidiffusion

### ISSUE THREAD

**Issue by EkaLinjas** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#40]
Seems the inpainting is not work with the extension.
![image](https://user-images.githubusercontent.com/125619279/226166075-ce6d4245-4d74-44d9-ac42-73e0a8bc8324.png)
![image](https://user-images.githubusercontent.com/125619279/226165978-f7f38d1a-b1f1-402b-89b7-8eaca9107660.png)
this is the setting i used.
Error code down below.
![image](https://user-images.githubusercontent.com/125619279/226166037-15c3ccdc-8c82-45aa-9dd7-e7ae893d3a55.png)
`Loading weights [7107c05c1c] from G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\dalcefoPainting_3rd.safetensors
Creating model from config: G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Model loaded in 1.7s (create model: 0.2s, apply weights to model: 0.4s, apply half(): 0.3s, load VAE: 0.1s, move model to device: 0.6s).
Upscaling image with ESRGAN_4x...
ControlNet found. MultiDiffusion ControlNet support is enabled.
MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 64 x 64 Tile batches: 42 Batch size: 1
Loading weights [3498c900ec] from G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\RPG_V4_inpainting.inpainting.safetensors
Creating model from config: G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\configs\v1-inpainting-inference.yaml
LatentInpaintDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.54 M params.
Loading VAE weights specified in settings: G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Model loaded in 1.6s (create model: 0.2s, apply weights to model: 0.5s, apply half(): 0.3s, load VAE: 0.2s, move model to device: 0.4s).
Error completing request
Arguments: ('task(sthhbj23vlzsi46)', 2, '<(masterpiece, realistic:1.3), (extremely intricate:1.2)>, portrait of a girl, (face:1.2), floting hair, wind, cloud, sunlight, cinematic light, bangs, <hypernet:dalcefo_nocopy_v2:0.8>', '(worst quality, low quality:1.4), (depth of field, blurry:1.2), (greyscale, monochrome:1.1), 3D face, cropped, lowres, text, jpeg artifacts, signature, watermark, username, blurry, artist name, trademark, watermark, title, multiple view, Reference sheet, curvy, plump, fat, muscular female, strabismus,', [], <PIL.Image.Image image mode=RGBA size=776x1016 at 0x1EF230B5900>, None, {'image': <PIL.Image.Image image mode=RGBA size=776x1016 at 0x1EF230B4CA0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=776x1016 at 0x1EF230B5810>}, None, None, None, None, 26, 15, 1, 0, 1, False, False, 1, 1, 8, 1.5, 0.4, -1.0, -1.0, 0, 0, 0, False, 680, 520, 0, 1, 16, 0, '', '', '', ['Model hash: 7107c05c1c'], 0, 0, 2, 512, 512, True, 'None', 'None', 0, 0, 0, 0, 0, 0.25, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, True, False, 0, -1, True, False, 1024, 1024, True, 64, 64, 32, 1, 'ESRGAN_4x', 2, False, True, False, True, False, 0, 3072, 192, False, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 'x264', 'mci', 10, 0, False, True, True, True, 'intermediate', 'animation', False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', True, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, '', 0.5, True, False, '', 'Lerp', False, False, 1, 0.3, False, 'OUT', ['OUT'], 5, 0, 'Nearest', False, 'Nearest', False, 'Lerp', '422', '156', False, False, False, 3, 0, False, False, 0, False, 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'first', -1, 1, 0, 1, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, False, 'Blur First V1', 0.25, 10, 10, 10, 10, 1, False, '', '', 0.5, 1, False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Use from inpaint tab, inpaint at full res ON, denoise <0.5</p>', 'None', 30, 4, 0, 0, False, 'None', '<br>', 'None', 30, 4, 0, 0, 4, 0.4, True, 32, None, True, None, None, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, True, True, None, None, None, None, None, 50, False, 4.0, '', 10.0, 'Linear', 3, False, True, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 10.0, True, 30.0, True, 0.0, 'Lanczos', 1, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False, '{inspiration}', None, 'linear', 'lerp', 'token', 'random', '30', 'fixed', 1, '8', None, 'Lanczos', 2, 0, 0, 'mp4', 10.0, 0, '', True, False, False, '', '', False, '', 127, False, 30, 9999, 1, 10, 0.25, True, False, '1', '', True, '', '', '', '', '', '', '', '', '', '', '', 'None', 0.3, 60) {}
Traceback (most recent call last):
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 984, in init
    image_masked.paste(image.convert("RGBA").convert("RGBa"), mask=ImageOps.invert(self.mask_for_overlay.convert('L')))
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\PIL\Image.py", line 1731, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
`
this is the full error code.

**Comment by pkuliyi2015** [comment]
Thank you for your feedback. The problem I have spotted and are likely to have fixed it in the dev
 branch. Will move to main branch after all new functions has been tested.

**Comment by pkuliyi2015** [comment]
Please update and test now, I'm not sure whether it is fine in this version.

**Comment by pkuliyi2015** [comment]
Should be compatible with masked-inpainting now.

**Comment by novaexe** [comment]
nope still happens

**Comment by hzy0110** [comment]
I have the same problem
Tiled Diffusion select upscaler will cause the same error, do not select can run.

**Comment by pkuliyi2015** [comment]
> I have the same problem Tiled Diffusion select upscaler will cause the same error, do not select can run. The plug-in has been updated to the latest

This is just a webUI preview error. I think your image should be still generated normally in your folder, despite the error.
