### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by kanyunzi1650** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#41]
Great extension. With tiled vae i can process 2048x2048 and even bigger images with 8gb vram. This is sorta gamechanging.
Thank you for your hard work.
I created issue because there is no discussions section.

**Comment by pkuliyi2015** [comment]
OK thank you for reminding. I just created a discussion session. This extension will have a very important update in no more than 24 hours. All new features has been prepared in the dev branch.
