### ISSUE TITLE
Losing contrast and details

### ISSUE THREAD

**Issue by Gagelee** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#43]
This extension is amazingly fast, andn making upsclar possible for low end machine, but there are some issues.I don not know whether it is the model I use or the parameters, I could not get the desired result. 
Firstly, it seems like the VAE (My VAE is nor named after the model I used) is not working as intended, the upscalar versioin looks much flatter, like  when the VAE is not working; And I do not know whether it is beacuse of the low contrast, I think the upscaled version looks less detailed than the orginal one. is it normal? can anybody tell me what I am doing wrong? Here is the before and after comparsion and all my settings.
models and prompts
![image](https://user-images.githubusercontent.com/19219684/226332247-8354bb33-f5ba-4fdb-85a6-defc1fc62038.png)
![image](https://user-images.githubusercontent.com/19219684/226332617-550b84d1-719f-45d9-b721-3701eec60133.png)
The original 
https://imgsli.com/MTYzMzk4
![下载](https://user-images.githubusercontent.com/19219684/226333306-04f18a2a-7f43-4b0b-ade3-4d129cad41bd.png)

![00044-1991595696](https://user-images.githubusercontent.com/19219684/226333318-870ef258-75eb-49fa-830a-9f6bc37b7bc4.png)

**Comment by Gagelee** [comment]
Thanks for the advice!  I am using a 8G GPU on the cloud, I am horrible at managing the memory fragmentaion and often times I will get the out of memory warning, after several trials it seems the limit is 1280 for 2x upscales and the faded effect went away! thanks for the help!
![00045-4126741770](https://user-images.githubusercontent.com/19219684/226395684-6cefe3f0-f639-4f5d-969f-e7e2c8e2057d.png)

and I have played with the denoise parmaters for a while, I am wondering in the future will this extension be able adding more details for blurred areas, or we can choose the strength of denoise in the region promt control?

**Comment by pkuliyi2015** [comment]
In fact, this extension is compatible with masked inpainting. It can redraw superlarge images but you have to do it multiple times if you want to use different denoise values. Doing at once is theoretically not possible.
