### ISSUE TITLE
不确定这个新功能的正确使用方法。

### ISSUE THREAD

**Issue by dajusha** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#45]
在 i2i 中将图拖进主框，然后拖进“Region Prompt Control”中的框（上面的按钮“从图生图导入”没有作用）。
用红框圈住图中画坏了的手，提示符填写 hand, 然后生成结果是整个图全部改变了。

重新试验，把图拖进 inpaint 的主框，拖进下方“Region Prompt Control”中的框，红框圈住手，提示符填写 hand，点击生成后等一下就报错：
denoised = latent * mask + nmask * denoised
RuntimeError: The size of tensor a (14) must match the size of tensor b (103) at non-singleton dimension 3

不知道为什么，感觉我用的方法不对。

**Comment by perorina** [comment]
i got this problem tho

**Comment by LightChaser666** [comment]
这是因为底层逻辑bug，尝试一下最新版本，我应该修复了

**Comment by pkuliyi2015** [comment]
修好了已经，你如果不想改别的位置，可以直接mask掉，单独重绘某个位置

**Comment by dajusha** [comment]
还是错误并且很困惑，过去想要不变其他地方，单独改局部，就用黑色涂抹要改的地方，然后生成就可以roll出目标。

现在用这个红框重绘局部是要怎么做？
Tiled Diffusion框是第一层，有个enable和放大系数。
Region Prompt Control框是第二层，有个enable和Background Multiplier，也是放大系数？
Region 1 红框开是第三层，仍有个enable和Multiplier，第三个系数了。

我现在把同一个图拖到图生图的局部重绘框，不涂抹，然后三层全enable，sampler用sde++ karras，第三层中用红框覆盖一块区域，三层中每一层放大系数都写1。
但是使用不同的放大算法，总是得到“ValueError: Coordinate 'right' is less than 'left' ” 这个错误。


迫切需要操作指南。

**Comment by pkuliyi2015** [comment]
有没有相应的截图呢这个报错
我肯定会做说明的呀，但是才把功能部分写完，并没有来得及写说明

**Comment by dajusha** [comment]
命令行窗口中最近一次是这样：

`[Tiled Diffusion] upscaling image with lollypop...
[Tiled Diffusion] ControlNet found, MultiDiffusion-ControlNet support is enabled.
Error completing request
Arguments: ('task(p43m8d7hiijfnn6)', 2, 'face, ', '', [], None, None, {'image': <PIL.Image.Image image mode=RGBA size=912x512 at 0x221CCED9240>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=912x512 at 0x221CCED9FF0>}, None, None, None, None, 30, 16, 4, 0, 1, False, False, 1, 3, 7, 1.5, 0.5, -1.0, -1.0, 0, 0, 0, False, 512, 912, 3, 1, 32, 0, '', '', '', [], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'lollypop', 1, False, True, 1, True, 1, 0.2269005847953216, 0.295833333333333, 0.2678362573099415, 0.3416666666666668, 'face,', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', True, True, True, True, 0, 960, 64, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.external_code.ControlNetUnit object at 0x00000221CD15F250>, <scripts.external_code.ControlNetUnit object at 0x00000221CD16FB20>, <scripts.external_code.ControlNetUnit object at 0x00000221CD1391B0>, <scripts.external_code.ControlNetUnit object at 0x00000221CD221E40>, <scripts.external_code.ControlNetUnit object at 0x00000221CD176EF0>, <scripts.external_code.ControlNetUnit object at 0x00000221CD1174F0>, <scripts.external_code.ControlNetUnit object at 0x00000221CD15F1C0>, <scripts.external_code.ControlNetUnit object at 0x00000221CD1D7460>, <scripts.external_code.ControlNetUnit object at 0x00000221CD184820>, <scripts.external_code.ControlNetUnit object at 0x00000221CD1BC0A0>, False, '', 0.5, True, False, '', 'Lerp', False, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, False, False, 3, 0, False, False, 0, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, None, False, None, False, None, False, None, False, None, False, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "D:\sd.webui\webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\sd.webui\webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\sd.webui\webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "D:\sd.webui\webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\sd.webui\webui\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "D:\sd.webui\webui\modules\processing.py", line 938, in init
    self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
  File "D:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 305, in create_sampler
    delegate.prepare_custom_bbox(global_multiplier, bbox_control_states)
  File "D:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 51, in prepare_custom_bbox
    super().prepare_custom_bbox(global_multiplier, bbox_control_states)
  File "D:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\abstractdiffusion.py", line 138, in prepare_custom_bbox
    Prepare custom bboxes for region prompt
TypeError: '<=' not supported between instances of 'str' and 'int'`

设置的截图：
![FireShot Capture 014 - Stable Diffusion - 127 0 0 1](https://user-images.githubusercontent.com/12206161/226493731-6cc84a38-bbbc-40fa-b24c-a788721a7eb4.png)

**Comment by pkuliyi2015** [comment]
这个报错是浏览器缓存问题。删了插件重新下载就好了，之后也不会发生

**Comment by dajusha** [comment]
发现了一个原因，只要在重绘中，**重绘区域**选择**蒙版**但是不涂蒙版黑色，就会出现以下错误。如果重绘**全图**就不会发生这个错误，但重绘结果和原图完全一样，红框圈起来好像没用。

`[Tiled Diffusion] upscaling image with 4x_foolhardy_Remacri...
[Tiled Diffusion] ControlNet found, MultiDiffusion-ControlNet support is enabled.
MultiDiffusion hooked into DDIM sampler. Tile size: 96x96, Tile batches: 2, Batch size: 1
Error completing request
Arguments: ('task(04t79nk0xe9pfdq)', 2, '', '', [], None, None, {'image': <PIL.Image.Image image mode=RGBA size=912x512 at 0x1E99F41A260>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=912x512 at 0x1E99F41A710>}, None, None, None, None, 20, 17, 4, 0, 1, False, False, 1, 2, 7, 1.5, 0.4, -1.0, -1.0, 0, 0, 0, False, 512, 912, 0, 1, 32, 0, '', '', '', [], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, '4x_foolhardy_Remacri', 1, False, True, 1, True, 1, 0.23859649122807025, 0.2958333333333334, 0.2327485380116959, 0.32500000000000007, 'face,', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', True, True, True, True, 0, 960, 64, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.external_code.ControlNetUnit object at 0x000001E99F443310>, <scripts.external_code.ControlNetUnit object at 0x000001E99F427F40>, <scripts.external_code.ControlNetUnit object at 0x000001E99F439720>, <scripts.external_code.ControlNetUnit object at 0x000001E99F49C5E0>, <scripts.external_code.ControlNetUnit object at 0x000001E99F447550>, <scripts.external_code.ControlNetUnit object at 0x000001E99F4509A0>, <scripts.external_code.ControlNetUnit object at 0x000001E99F454190>, <scripts.external_code.ControlNetUnit object at 0x000001E99F5B3B80>, <scripts.external_code.ControlNetUnit object at 0x000001E99F43EFB0>, <scripts.external_code.ControlNetUnit object at 0x000001E99F5BBE80>, False, '', 0.5, True, False, '', 'Lerp', False, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, False, False, 3, 0, False, False, 0, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, None, False, None, False, None, False, None, False, None, False, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "D:\sd.webui\webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\sd.webui\webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\sd.webui\webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "D:\sd.webui\webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\sd.webui\webui\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "D:\sd.webui\webui\modules\processing.py", line 959, in init
    mask = mask.crop(crop_region)
  File "D:\sd.webui\system\python\lib\site-packages\PIL\Image.py", line 1228, in crop
    raise ValueError(msg)
ValueError: Coordinate 'right' is less than 'left'`

**Comment by pkuliyi2015** [comment]
测试最新版本，我修复了大多数的bug

**Comment by dajusha** [comment]
> 测试最新版本，我修复了大多数的bug

谢谢，能否简单解释一下红框内部分精细化的基本用法？最简单的步骤就行。

**Comment by dajusha** [comment]
感谢新的英文 t2i 区域说明，试用后产生了疑问：
使用几个框体绘画时，多个框体之间过于独立了，从构图和姿态上都不发生互动。
没做到例图中两个人坐沙发那种效果……有什么方法改善吗？还是就靠大量作图 roll 出合适的？

**Comment by pkuliyi2015** [comment]
如果你框体之间是完全分开的那还真没办法，只能靠controlnet openpose。

示例图有取巧，首先人物框体有大概五分之一面积彼此重叠，加大了互动概率，其次是背景prompt中有个沙发，而两个人prompt都是坐在沙发上，如果沙发生成的位置合适，那么她们俩大概率就会坐在同一个沙发上了（狗头）。使用这种办法出图概率极高，平均两张就能出一张这样的图。

**Comment by dajusha** [comment]
> 
我明白一点了……
请问是否推荐在顶部的主提示框里写常用的起手？还是把它们分布到背景和各个主体的小提示框里？
然后大框留空？

**Comment by pkuliyi2015** [comment]
在实际效果上是一样的，因为插件开始计算之前会做一个拼接。不过使用的时候，写在上面能省去不少文字。

**Comment by dajusha** [comment]
测试发现常用的起手会导致局部框内画作变成局部特写，进一步导致无法合理拼合……
如果把起手去掉虽然画的差但是能拼起来。

**Comment by dajusha** [comment]
另外写在局部框里的提示词不会出现在图像的txt副本里，希望这个能做一下

**Comment by pkuliyi2015** [comment]
主要是暂时没啥空哈哈哈 有空做
