### ISSUE TITLE
Please enable 'Move VAE to GPU' to use Tiled VAE.

### ISSUE THREAD

**Issue by jurandfantom** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#47]
To be honest, I was looking for that setting and no clue where it might be. What exactly is expected from me?
Ps. hope it will be added to readme about "method"

![23,03,20 - 22,35,55 - 7441 a](https://user-images.githubusercontent.com/30580568/226481022-93a45424-abef-4278-a31f-38d2bd197ad9.png)

**Comment by jurandfantom** [comment]
And second batch of errors (when picked VAE from list - but that force me to use VAE ).
![23,03,20 - 22,42,54 - 7442 a](https://user-images.githubusercontent.com/30580568/226481881-a623a408-3f6a-498f-a9d3-6a905085ed9a.png)
![23,03,20 - 22,43,31 - 7443 a](https://user-images.githubusercontent.com/30580568/226481903-76f29725-cf3f-40d7-9775-11dd3dc922be.png)

**Comment by jurandfantom** [comment]
above message appear for mode "mixture of diffusers" only.

**Comment by pkuliyi2015** [comment]
Hello, are you using the latest commit [25600e0](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/25600e03fb5bdbd3376175908856ca73208f8abc)? 

I fixed most logical errors now and is ready to write a new README. Please check whether the bug still exists in this latest version.

**Comment by jurandfantom** [comment]
all works indeed (i was referring to version that was updated 4h ago - everybody update everything all time.)  But lets keep it just in case somebody else find similar issue.

**Comment by pkuliyi2015** [comment]
In fact I also use the extension myself. 
The latest version has less bugs, with a powerful regional prompt control, so you can focus on one part to redraw. All functions are compatible with masked-inpainting, so when some part of the result is not very ideal, you just mask that part and let it draw again. The result is quite pleasing.

**Comment by pkuliyi2015** [comment]
Oh refresh your browser please

**Comment by jurandfantom** [comment]
glad to hear that (about updates).
So i gut hub couple seconds ago (and I can see another update), but error still appear. Turned off firefox complete (to refresh browser)
"TypeError: '<=' not supported between instances of 'str' and 'int'"

**Comment by pkuliyi2015** [comment]
Would you mind delete the extension and download again? I confirmed that my code has been fixed. Or you try another browser (chrome or edge?)

I also feel weird.

**Comment by jurandfantom** [comment]
delete and redownload fix everything, even upscale by x4 :)
Now there is need of make video (without commentary) that shows correct workflow on couple examples - easiest way that help most :) 

great job with everything.

**Comment by pkuliyi2015** [comment]
Please update as the previous version has a crucial logical error; it cannot draw multiple regions, because it uses positive prompts as negative prompt and ruins the region. After updating it should work very well.
