### ISSUE TITLE
Ignoring controlnet

### ISSUE THREAD

**Issue by srandovnidobrodruzstvi** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#49]
Hey, you guys are awesome!  
..I would like to ask for a little help, how to use controlnet? 

With any denoising it doesn't care about the input image, as if controlnet doesn't work at all. I've tried all combinations of everything:) 

Steps: 40, Sampler: DDIM (tried all) , CFG scale: 3.5 (tried all) , Seed: 410819813, Size: 1024x1024, Model hash: 710fc74d4c (Protogen), Denoising strength: 0. 87 (tried all), Mask blur: 4, ControlNet-0 Enabled: True, ControlNet-0 Module: canny, ControlNet-0 Model: control_sd15_canny [fef5e48e] (tried the same input image and a different), ControlNet-0 Weight: 1 (tried 2), ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1, Tiled Diffusion upscaler: ESRGAN_4x, Tiled Diffusion scale factor: 2, Tiled Diffusion tile width: 96, Tiled Diffusion tile height: 96, Tiled Diffusion overlap: 48  

ON:  xformers 
OFF: medvram, always-batch-cond-uncond, no-half, no-half-vae 

Thanks 
Mira

**Comment by pkuliyi2015** [comment]
Please test the latest version where I fixed tons of bugs.
