### ISSUE TITLE
Help with wide images

### ISSUE THREAD

**Issue by ppietro21** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#5]
Hi, thanks for this amazing project, I saw this wide image generation I think is amazing, on the instructions I find this:

"Wide Image Generation (txt2img)
txt2img panorama generation, as mentioned in MultiDiffusion.
All tiles share the same prompt currently.
Please use simple positive prompts to get good results, otherwise the result will be pool.
We are urgently working on the rectangular & fine-grained prompt control.
Example - masterpiece, best quality, highres, city skyline, night.
"

But can you describe how can I generate this wide images step by step on automatic 1111? it's on the Multidiffusion section?

Br,
Pablo.

**Comment by LightChaser666** [comment]
Yes, it is. To reproduce the city panorama, just go to the txt2img tab.
I
n positive prompt you type in: masterpiece, best quality, highres, city skyline, night.
In negative prompt you use some regular prompt (I use the textual inversion "Easy Negative" for convenience).
For fast speed you can use 20~25 steps.

Next, enable the MultiDiffusion, tick the Overwrite Image Size, and then set height to 512, width to 4096.
Tile size 64, overlap 32. And then you can start the generation.

It's noteworthy that, currently the MultiDiffusion works well for wide images, but not good at all for tall images. This should be improved after I implement the regional prompt control, which allows you to define something like "sky" "building" "ground', as well as "head, upper body, chest, legs, foots". I'm still trying on this.

Good luck!

**Comment by pkuliyi2015** [comment]
Also thank you for using.
