### ISSUE TITLE
新版这个界面设置看不懂了！

### ISSUE THREAD

**Issue by Myoko** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#50]
新版这个界面设置看不懂了！ 试了一下 怎么搞都觉得放大后的人物脸不够清晰,不知道是一处的参数没有设置正确？
![1](https://user-images.githubusercontent.com/3013386/226623121-698d900d-380f-41ef-a8e6-10f04d91750b.png)
放大后
![00002-2316095145](https://user-images.githubusercontent.com/3013386/226623190-4fada37c-65b6-48fe-a55c-c8b2493ab85e.png)

左边原图右边放大后 眼睛不如原图
![未命名](https://user-images.githubusercontent.com/3013386/226656696-709c22b9-e404-4580-b3b1-615722f8a193.png)

**Comment by pkuliyi2015** [comment]
我简化了一下设置，但现阶段要取得更好的放大效果不太可能，需要等我实现一点新技术才行。

**Comment by xuhao1** [comment]
@pkuliyi2015 Hi, I just can't foud the upsampling option. Is this correct?

**Comment by pkuliyi2015** [comment]
The upsampling option is only available in i2i
