### ISSUE TITLE
My checkpoint (abyssorangemix3AOM3_aom3a1b.safetensor) shows noise under Tiled Diffusion(img2img).

### ISSUE THREAD

**Issue by AH225D** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#56]
Just like this.Wooden floor turned into barnacles.
![image](https://user-images.githubusercontent.com/97416394/227248108-f80c6823-cd87-4e2d-8ffb-8c0828b1fc3f.png)
Stockings become cracked walls
![image](https://user-images.githubusercontent.com/97416394/227248461-9176cb4b-6873-4187-bb32-a46b3369d0da.png)
I've tried several settings, but none of them work well
![image](https://user-images.githubusercontent.com/97416394/227250003-cb7d79a3-8b10-4532-87e9-54dc5559a5dd.png)
Steps: 50, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3929348709, Size: 2048x2048, Model hash: 5493a0ec49, Denoising strength: 0.4, Clip skip: 2, ENSD: 31337, Mask blur: 4, Tiled Diffusion upscaler: ESRGAN_4x, Tiled Diffusion scale factor: 2, Tiled Diffusion tile width: 96, Tiled Diffusion tile height: 96, Tiled Diffusion overlap: 48
![image](https://user-images.githubusercontent.com/97416394/227251728-96ad6f87-9cd2-4c3a-8e1f-be07dbabd2ba.png)
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 750716271, Size: 2048x2048, Model hash: 5493a0ec49, Denoising strength: 0.4, Clip skip: 2, ENSD: 31337, Mask blur: 4, Tiled Diffusion upscaler: Nearest, Tiled Diffusion scale factor: 2, Tiled Diffusion tile width: 96, Tiled Diffusion tile height: 96, Tiled Diffusion overlap: 48
![image](https://user-images.githubusercontent.com/97416394/227254231-3911db2b-57a3-42db-8370-1f87f6f6c2ad.png)
Steps: 25, Sampler: DPM++ 2M Karras, CFG scale: 14, Seed: 2795935609, Size: 2048x2048, Model hash: 5493a0ec49, Denoising strength: 0.4, Clip skip: 2, ENSD: 31337, Mask blur: 4, Tiled Diffusion upscaler: Nearest, Tiled Diffusion scale factor: 2, Tiled Diffusion tile width: 96, Tiled Diffusion tile height: 96, Tiled Diffusion overlap: 48

Adjusting Steps or Tiled Diffusion upscaler or CFG Scale,neither can curb this trend.

But when I use hires.fix, is not so obvious,
![image](https://user-images.githubusercontent.com/97416394/227267423-17c57bdf-b159-487e-9294-b5e677f269c6.png)
Steps: 50, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3505390930, Size: 1024x1024, Model hash: 5493a0ec49, Denoising strength: 0.5, Clip skip: 2, ENSD: 31337, Tiled Diffusion tile width: 96, Tiled Diffusion tile height: 96, Tiled Diffusion overlap: 48, ControlNet Enabled: True, ControlNet Module: depth, ControlNet Model: control_depth [bda98948], ControlNet Weight: 1, ControlNet Guidance Start: 0, ControlNet Guidance End: 1, Hires upscale: 1.5, Hires steps: 20, Hires upscaler: Latent (nearest-exact)
(I can only upsample to 1536x1536 when using hires.fix, due to the memory of the graphics card)

Is there a way to reduce the memory footprint of hires.fix without lowering the output resolution? Avoid "RuntimeError: Not enough memory, use lower resolution"? 
Or could you add Latent (nearest-exact) to Tiled Diffusion so that it can use the upsampling settings recommended by the OrangeMixs developers?↓
"Upscaler:
Detailed illust → Latenet (nearest-exact)
Denoise strength: 0.5 (0.5~0.6)"

Or something else will do

**Comment by pkuliyi2015** [comment]
Please test the latest version where I fixed tons of bugs. 
However, I still need time to implement new techniques for better upscaling quality.
