### ISSUE TITLE
Foreground and Background

### ISSUE THREAD

**Issue by svupper** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#60]
Hello What is this new feature ?

**Comment by pkuliyi2015** [comment]
Previously, if you draw a region overlapping with a background, it just blends your foreground and background in a very harsh way (1/2 + 1/2). The average usually ruins your foreground and produces unpleasant seams. 

With the latest Foreground and Background option, we dig holes on the background, put your foreground region in, and smooth its edges with feather radius you give. In this way, your foreground character / object can smoothly and perfectly fuses in any background you want now. This is an unprecedental algorithm that no other extension can provide, even latent couples.

Here is an example of fusing a cyberpunk monster into a natural sea background:

![image](https://user-images.githubusercontent.com/59076257/227586138-1a2e52a3-7448-4086-8f2e-bd90a9caadf9.png)

**Comment by svupper** [comment]
Wow, very nice work. Does it mean you have to create a region for the whole image as a background image and one(or more) foreground regions?

**Comment by pkuliyi2015** [comment]
If your vram is enough you can use a single large background. However if not, you can use multiple region with some overlap to fill your canvas. It’s very flexible.

**Comment by svupper** [comment]
Ok, because I thought if I don't create a background of the whole image, it will not generate anything in it. It happened to me in my first try. I ended up with just my foreground regions and nothing elsewhere, I'm still wondering why
