### ISSUE TITLE
Cannot read configuration from ui-config.json

### ISSUE THREAD

**Issue by runo0044** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#64]
"customscript/vae_optimize.py/txt2img/Enable/visible": true,
    "customscript/vae_optimize.py/txt2img/Enable/value": true,
    "customscript/vae_optimize.py/txt2img/Move VAE to GPU/visible": true,
    "customscript/vae_optimize.py/txt2img/Move VAE to GPU/value": true,
    "customscript/vae_optimize.py/txt2img/Encoder Tile Size/visible": true,
    "customscript/vae_optimize.py/txt2img/Encoder Tile Size/value": 1024,
    "customscript/vae_optimize.py/txt2img/Encoder Tile Size/minimum": 256,
    "customscript/vae_optimize.py/txt2img/Encoder Tile Size/maximum": 4096,
    "customscript/vae_optimize.py/txt2img/Encoder Tile Size/step": 16,
    "customscript/vae_optimize.py/txt2img/Decoder Tile Size/visible": true,
    "customscript/vae_optimize.py/txt2img/Decoder Tile Size/value": 128,
    "customscript/vae_optimize.py/txt2img/Decoder Tile Size/minimum": 48,
    "customscript/vae_optimize.py/txt2img/Decoder Tile Size/maximum": 512,
    "customscript/vae_optimize.py/txt2img/Decoder Tile Size/step": 16,
    "customscript/vae_optimize.py/txt2img/Fast Encoder/visible": true,
    "customscript/vae_optimize.py/txt2img/Fast Encoder/value": false,
    "customscript/vae_optimize.py/txt2img/Fast Decoder/visible": true,
    "customscript/vae_optimize.py/txt2img/Fast Decoder/value": true,
    "customscript/vae_optimize.py/txt2img/Encoder Color Fix/visible": false,
    "customscript/vae_optimize.py/txt2img/Encoder Color Fix/value": 0,

I always use Tiled VAE and have set it up this way. However, this setting is not reflected.
Is this a bug? Or is my setting wrong?

**Comment by pkuliyi2015** [comment]
This is weird cause I also use it in this way. I would like to check out what happened.

**Comment by runo0044** [comment]
Thank you. 
Additional information.

My environment.
WebUI [a9fed7c]
a1111-sd-webui-locon 52c730a0 (Sat Mar 25 09:49:15 2023)
images-browser c902cffb (Sun Oct 30 09:04:46 2022)
multidiffusion-upscaler-for-automatic1111 554f9e85 (Sat Mar 25 08:03:32 2023)
sd-extension-system-info 907887c5 (Sat Mar 25 16:17:26 2023)
sd-webui-controlnet 241c05f8 (Thu Mar 23 15:18:35 2023)
sdweb-easy-prompt-selector 71346618 (Sat Feb 18 09:30:31 2023)
seed_travel a72c836c (Thu Mar 23 17:06:59 2023)
stable-diffusion-webui-anti-burn 4d678f1f (Sun Feb 19 19:22:44 2023)
stable-diffusion-webui-model-toolkit 8d8f073f (Fri Feb 17 20:39:41 2023)
stable-diffusion-webui-visualize-cross-attention-extension 5fb1e8f8 (Sun Dec 11 15:19:31 2022)

    "customscript/tilediffusion.py/txt2img/Enable/value": false,
   
The above settings in tilediffusion.py are reflected correctly, but not in vae_optimize.py.
