### ISSUE TITLE
Abnormal img2img with Tiled Diffusion and Region Prompt Control.

### ISSUE THREAD

**Issue by linanwx** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#65]
你好，在我更新到3月25号的版本之后，在img2img功能中开启Tiled Diffusion并开启Region Prompt Control之后，出现了异常现象，只有当Draw tiles as background (SLOW but save VRAM)选项开启时，才能正确生成图像，否则，除了被选中区域外，其他区域会变成褐色。我尝试恢复至3月22号的版本后，发现没有这个问题。

Hello. After updating to the version released on March 25th, I encountered an issue with the img2img function. Specifically, when I enabled Tiled Diffusion and Region Prompt Control, the generated images had an abnormal appearance. The issue only seems to be resolved when the "Draw tiles as background (SLOW but save VRAM)" option is enabled. If this option is not enabled, all areas except for the selected region turn brown.

I tried reverting to the version released on March 22nd, and I did not experience this issue.

![00043-844798863](https://user-images.githubusercontent.com/16589958/227731420-533804cc-2196-406e-9d60-36b123e61301.png)

**Comment by pkuliyi2015** [comment]
这不是bug而是默认行为。当你不开启那个选项的时候，你需要用自己的框来填满整个画布。我会在新的说明中标注出这一点。

**Comment by linanwx** [comment]
谢谢大大，爱你😘
