### ISSUE TITLE
Anyway to control seed for regions 

### ISSUE THREAD

**Issue by faisalhr1997** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#70]
Instead of regenerating the whole image i just want it locked so that only one region generates random seed

**Comment by pkuliyi2015** [comment]
Great idea. In fact, I'm also investigating the noise injection process. I want to see if we can fix the noise of one region, and largely keep the region's content. You can see my updated README's current progress (including a new Chinese README, a noise inverse, and a param saving), but this really takes time so I have some friends to help me.

**Comment by pkuliyi2015** [comment]
Well, here are some exciting initial results. I think I'm doing something revolutionary in terms of compositional generation.

The character with a seed:

![image](https://user-images.githubusercontent.com/59076257/227844833-48f54eba-f9b4-4c5b-9485-c467322d02aa.png)

Put she into the background:

![image](https://user-images.githubusercontent.com/59076257/227844969-62f10ac9-5beb-4bfe-98e6-afc64079856a.png)

**Comment by pkuliyi2015** [comment]
Updated the noise seed control feature, together with a noise inversion technology.
