### ISSUE TITLE
用Tiled Diffusion来放大，成品图颜色问题的原因

### ISSUE THREAD

**Issue by dajusha** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#72]
一个观察：
单独选择启用Tiled VAE来做小图，不勾选“编码器颜色修复/Encoder Color Fix”，成品没问题。勾选“Tiled Diffusion”和“Tiled VAE”，但仍不勾选“编码器颜色修复/Encoder Color Fix”，大图颜色会变淡。
勾选“Tiled Diffusion”和“Tiled VAE”，同时勾选“编码器颜色修复/Encoder Color Fix”，大图颜色正常。

感觉可能不合逻辑，如果Tiled VAE做的小图勾不勾选“编码器颜色修复/Encoder Color Fix”是无所谓的，而“Tiled Diffusion”的放大功能却需要勾选“编码器颜色修复/Encoder Color Fix”来正常工作。

或许应该把这个选项放进“Tiled Diffusion”的选项页面？

**Comment by pkuliyi2015** [comment]
颜色问题纯粹是因为encoder tile size很小（比如256）导致的VAE方差估计问题。小图嘛不需要估计也是准的，因此这也是为啥你成品没问题。而大图再这么估计就会出事，某些通道方差巨大，颜色发灰。

所以我在VAE里引入了半快速模式，仅仅把前面11步最慢的运算做估计，后面就不估了。这个功能写在页面上，叫做颜色修复。然而它并不是一个颜色美化的后期处理，而是直接改变了Tiled VAE的算法流程，因此技术上不可能放进Tiled Diffusion。

希望这个技术解释能解答你的疑惑。

**Comment by dajusha** [comment]
> 颜色问题纯粹是因为encoder tile size很小（比如256）导致的VAE方差估计问题。小图嘛不需要估计也是准的，因此这也是为啥你成品没问题。而大图再这么估计就会出事，某些通道方差巨大，颜色发灰。
> 
> 所以我在VAE里引入了半快速模式，仅仅把前面11步最慢的运算做估计，后面就不估了。这个功能写在页面上，叫做颜色修复。然而它并不是一个颜色美化的后期处理，而是直接改变了Tiled VAE的算法流程，因此技术上不可能放进Tiled Diffusion。
> 
> 希望这个技术解释能解答你的疑惑。

原来这样……那么有没有可能，做一个可选项，允许当开启Tiled Diffusion的时候，自动开启vae颜色修正（如果还没开）？

**Comment by pkuliyi2015** [comment]
很麻烦，gradio控件互相交互烂成狗。你鼠标点一下的事情，我几十行都未必搞得定 QAQ

**Comment by dajusha** [comment]
> 很麻烦，gradio控件互相交互烂成狗。你鼠标点一下的事情，我几十行都未必搞得定 QAQ

也行，至少明白了原因
