### ISSUE TITLE
txt2img Generating Multiple Subjects

### ISSUE THREAD

**Issue by altoiddealer** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#73]
Hello, I was enjoying this extension the past 2 days without problems

As of this morning, suddenly the extension is not working correctly.

Automatic1111 is up to date, along with my extensions (not many).

Every image I try to generate results in a blurry multi-subject result.

I tested different checkpoints.
I tried uninstalling and deleting the "multidiffusion-upscaler-for-automatic1111" folder, and reinstalling again, but the issue persists.

I really like this extension, so I'm hoping there is some kind of fix for this.

<img width="1664" alt="Screenshot 2023-03-27 212802" src="https://user-images.githubusercontent.com/1613484/228103493-c628a7a0-63ba-4a06-b627-a2f2ea01bac8.png">

<img width="1106" alt="Screenshot 2023-03-27 213525" src="https://user-images.githubusercontent.com/1613484/228104323-98be9e5e-e772-4db9-b131-33a90bb96be9.png">

<img width="796" alt="Screenshot 2023-03-27 213838" src="https://user-images.githubusercontent.com/1613484/228104486-b900c9de-43cc-4cd4-9c06-81b657e8693c.png">

**Comment by pkuliyi2015** [comment]
Oh this is related to your resolution and you cannot include concrete objects in your main prompt. Please read the readme carefully and you'll find how to use.

**Comment by altoiddealer** [comment]
Thanks for the reply.  I’ll probably close this very shortly… I thought that only applied to the img2img usage.

I wasn’t having issues before with txt2img.  But now that I think about it, I think I was always using Controlnet.  But these gens were without cnet.  Perhaps cnet prevents the duplicates in some cases

**Comment by pkuliyi2015** [comment]
You have to use some guidance to prevent the toddling from generating your prompt everywhere. ControlNet is one of the guidance. And if you like, The regional problem can be another kind of guidance.
