### ISSUE TITLE
how to deal with this problem?

### ISSUE THREAD

**Issue by zskm01** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#79]
first ,sometime The program will get stuck here, I don't know if it's related to insufficient video memory
![微信截图_20230329143226](https://user-images.githubusercontent.com/125043027/228435931-80c2b62c-e283-4fd5-94a9-8dcc527aa1e8.png)
second,seemingly the Region Prompt Control don't seem work ,The image generated after I input prompt in the box has nothing to do with prompt
![微信截图_20230329143639](https://user-images.githubusercontent.com/125043027/228436558-3a16b39a-39f1-4e1b-b169-fd188eaa439c.png)

**Comment by zskm01** [comment]
![微信截图_20230329143743](https://user-images.githubusercontent.com/125043027/228436708-f9856d03-d7d2-43a3-bdb7-0b235df506ac.png)
Has nothing to do with prompt

**Comment by pkuliyi2015** [comment]
You can use MultiDiffusion to generate each region separately first (each time you try one region). If the content is not you want, you need to adjust your prompt.
