### ISSUE TITLE
Region Prompt Control is always enabled if "customscript/tilediffusion.py/img2img/Enable/value": true

### ISSUE THREAD

**Issue by SD-fan** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#82]
I've set tilediffusion and VAE enabled by default for img2img via ui-config.json:

-- snip from ui-config.json --
```
    "customscript/tilediffusion.py/img2img/Enable/visible": true,
    "customscript/tilediffusion.py/img2img/Enable/value": true,
    "customscript/tilediffusion.py/img2img/Method/visible": true,
...
    "customscript/vae_optimize.py/img2img/Enable/visible": true,
    "customscript/vae_optimize.py/img2img/Enable/value": true,
    "customscript/vae_optimize.py/img2img/Move VAE to GPU/visible": true,
    "customscript/vae_optimize.py/img2img/Move VAE to GPU/value": true,
```
-- end snip --

Unfortunately Region Prompt Control also gets enabled by default with this. As I only want to upscale I need to disable Region Prompt Control manually every time. 

Would be great to have a variable in ui-config.json to set the default for Region Prompt Control as well - or just fix this behaviour/bug to not enable Region Prompt Control. 

Thanks much! Love your extension btw. Best of all upscalers I've tried. Good work!!

**Comment by pkuliyi2015** [comment]
Fixed in the latest version by changing the label name of these options.
