### ISSUE TITLE
测试了一下新加入的 Tiled Noise Inversion 功能，人物很棒，但是背景似乎有些过度锐化

### ISSUE THREAD

**Issue by neavo** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#85]
从上到下分别是原图（1920x1080）、使用新算法放大后的图片、未使用新算法放大后的图片
主要看天空，中图有很明显的切片断层痕迹，而且似乎有一些过渡锐化，不过人物和近景的表现确实不错
不知道这是否符合设计预期？

![00048-651127374](https://user-images.githubusercontent.com/998676/228784829-780fa695-1d01-472a-beb1-a36ce516f21a.png)
![00049-2426310728](https://user-images.githubusercontent.com/998676/228784855-6f3c3037-f811-48d0-81d3-47c2dc7d61fb.png)
![00051-3832051193](https://user-images.githubusercontent.com/998676/228784863-fedcd238-4342-4d90-a491-a6c1be42b15d.png)

**Comment by neavo** [comment]
确实是 Mixture of diffusers，具体设置如下

![QQ截图20230330170749](https://user-images.githubusercontent.com/998676/228787200-65759256-2cc3-40cd-96a6-ae375e33ee14.png)

不过缝隙这是个小问题，有很多办法可以解决，主要是感觉背景过于锐化了，已经改变了原本的绘画风格

**Comment by pkuliyi2015** [comment]
实际上我也没法控制具体会不会锐化。我跑的结果差不多是这样，只是把renoise关掉，denoise调成0.3，retouch调成5

![00106-2771983618](https://user-images.githubusercontent.com/59076257/228793906-1254dcab-b778-459b-9878-35f0a05c7e52.jpeg)

新算法主要是在人物图上比较好使。放大自然风景星空房屋什么的是不行的，可能还不如RealESRGAN（笑）

**Comment by pkuliyi2015** [comment]
我只是算法的实现者，而且retouch也是误打误撞发现的，自己也不知道有没有好参数，全靠穷举（狗头）
刚刚发现retouch=3-4，denoise=0.35, CFG = 1 是非常好的参数。正在利用这个出新图，而且考虑更新默认参数和提示。

**Comment by Raz0rStorm** [comment]
这noice inversion不是没√上吗

**Comment by pkuliyi2015** [comment]
这个看你是什么类型的图。如果是真人照片，直接勾选然后用默认参数即可。如果是二次元，建议retouch=3 CFG=1或者2 denoise=0.35

**Comment by neavo** [comment]
> 请问一下NI怎么用？ 看图里好像noice inversion没√上吧

截图的时候忘记勾上了，实际跑上面的示例图的时候是勾上的

**Comment by dajusha** [comment]
> 这个看你是什么类型的图。如果是真人照片，直接勾选然后用默认参数即可。如果是二次元，建议retouch=3 CFG=1或者2 denoise=0.35

在readme中提及“利用 Tiled Diffusion 来放大或重绘图像”时采用高CFG例如14。那么在图生图放大，当同时开启Tiled Diffusion和Tiled Noise Inversion时，CFG应如何设置？

**Comment by pkuliyi2015** [comment]
已经更新 相信效果会有明显改善

**Comment by pkuliyi2015** [comment]
> > 这个看你是什么类型的图。如果是真人照片，直接勾选然后用默认参数即可。如果是二次元，建议retouch=3 CFG=1或者2 denoise=0.35
> 
> 在readme中提及“利用 Tiled Diffusion 来放大或重绘图像”时采用高CFG例如14。那么在图生图放大，当同时开启Tiled Diffusion和Tiled Noise Inversion时，CFG应如何设置？

最新的版本对CFG不敏感了。可以任意调试观察效果。我这边7-14都是正常的

**Comment by dajusha** [comment]
> > > 这个看你是什么类型的图。如果是真人照片，直接勾选然后用默认参数即可。如果是二次元，建议retouch=3 CFG=1或者2 denoise=0.35
> > 
> > 
> > 在readme中提及“利用 Tiled Diffusion 来放大或重绘图像”时采用高CFG例如14。那么在图生图放大，当同时开启Tiled Diffusion和Tiled Noise Inversion时，CFG应如何设置？
> 
> 最新的版本对CFG不敏感了。可以任意调试观察效果。我这边7-14都是正常的

提醒一下，retouch值没有记录在图同名txt文件

**Comment by pkuliyi2015** [comment]
感谢提醒 已经修复
