### ISSUE TITLE
Require for Communication

### ISSUE THREAD

**Issue by Huaxingweichen** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#9]
Hello, I'm a MS student at Peking University and very interested in your repo.
Could I have your e-mail or WeChat for the further communication?
My e-mail is huanghao@stu.pku.edu.cn. Thanks!

**Comment by pkuliyi2015** [comment]
Emailed with thanks.

**Comment by antonioo-c** [comment]
@pkuliyi2015 Hi! Thanks for your great work!
I am also a PKU student but undergraduated. Can I have your contact too? My email address would be antonchen@pku.edu.cn, thanks a lot!
