### ISSUE TITLE
Multi Diffusion在高倍率重绘的情况下导致部分区块过度锐化/虚化/涂抹

### ISSUE THREAD

**Issue by QR-0W** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#90]
我有一张图片，在利用i2i重绘，4X放大，开启Tiled VAE、MultiDiffusion（不是Mixture Of Diffusers）的情况下，如下所示，会产生部分场景出现不符合预期的锐化/虚化/涂抹，比如在下图所示的红圈中，建筑物的一部分被涂抹掉了。
<img width="1099" alt="屏幕截图 2023-03-31 225227" src="https://user-images.githubusercontent.com/84510337/229155583-51072f5e-0b33-4504-a5cb-0f3f3620ec51.png">
下面这张是2X放大的情况，可以看出在2X重绘的情况下则没有产生建筑物被涂抹掉的情况。
<img width="963" alt="屏幕截图 2023-03-31 225727" src="https://user-images.githubusercontent.com/84510337/229156285-598ced33-4653-44ff-86f1-c8864ec65e46.png">
我如果没有记错的话，在i2i重绘时，我的区块大小设置为128*128，重叠设置为96。我觉得这个大小并不算小？

**Comment by pkuliyi2015** [comment]
确认代码有bug 正在修复

**Comment by pkuliyi2015** [comment]
已经更新 相信效果有明显改善
