### ISSUE TITLE
Region Numbers are Mislabeled in GUI

### ISSUE THREAD

**Issue by altoiddealer** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#91]
First and foremost, your extension is AMAZING.

I just want to point out that the labelling for the region controls do not match.

<img width="944" alt="Screenshot 2023-03-31 111244" src="https://user-images.githubusercontent.com/1613484/229160118-18a4a3be-f002-4b92-bcff-77b79836cd2d.png">

**Comment by pkuliyi2015** [comment]
Thanks for the feedback. Will fix together with other problems.

**Comment by pkuliyi2015** [comment]
Fixed with thanks.
