### ISSUE TITLE
Unique IDs missing from most elements

### ISSUE THREAD

**Issue by sgriosadair** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#92]
Title kind of says it all.

But most of the elements don't have unique IDs. This makes it impossible to use other extensions/scripts with this which is a shame because it is easily one of the best extensions for automatic1111.

It would be awesome if we could get unique IDs on all the elements! Thank you.

**Comment by pkuliyi2015** [comment]
Will fix and push in the latest update.

**Comment by pkuliyi2015** [comment]
Fixed with thanks.
