### ISSUE TITLE
不同分区能使用不同lora模型吗？

### ISSUE THREAD

**Issue by wzgrx** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#94]
还是说多分区只能生成一个lora模型的角色

**Comment by pkuliyi2015** [comment]
能使用多个lora模型。但是我听闻最新webui版本似乎会有报错，得用稍微老一点的才行

**Comment by wzgrx** [comment]
> 能使用多个lora模型。但是我听闻最新webui版本似乎会有报错，得用稍微老一点的才行。你需要在prompt里面包含Lora。

好的，谢谢
