### ISSUE TITLE
A blurry image is generated when using the Region Prompt Control.

### ISSUE THREAD

**Issue by toyxyz** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#95]
A blurry image is generated when using the Region Prompt Control. If two or more Foregrounds are used, a completely blurry image is created. Is there something I'm missing? 
webui Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
multidiffusion : 26191a6b53312bd8993b020fa45ad35fd8b4c61e
![image](https://user-images.githubusercontent.com/8006000/229329096-794fee56-eb3e-413b-a62b-1c74da98bea8.png)
![image](https://user-images.githubusercontent.com/8006000/229329130-4c76a24d-e018-4561-a3c1-6a7c0850d543.png)

![image](https://user-images.githubusercontent.com/8006000/229329102-2dd36c77-13db-4659-b947-100ab389cf5f.png)
![image](https://user-images.githubusercontent.com/8006000/229329104-cac95471-e4c8-44a4-83ac-ec97c01a06fb.png)

**Comment by pkuliyi2015** [comment]
Thanks for your comment. I confirmed that this is a bug and will fix it very soon.

**Comment by pkuliyi2015** [comment]
Fixed with thanks.
