### ISSUE TITLE
Extension causes slowness

### ISSUE THREAD

**Issue by guzuligo** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#96]
Even when the extension is disabled, the generated image makes a long pause because it appears.

The extension shouldn't interfere with generated image when it is disabled.

Try removing the extension and see the speed of the generated image.

**Comment by guzuligo** [comment]
Wrong extension

**Comment by pkuliyi2015** [comment]
What happened?

**Comment by guzuligo** [comment]
It seems that when I enable this with controlNet, I get a very slow image generation.

**Comment by guzuligo** [comment]
By enabled, I mean enabled in the extensions tab. The issue exists even if they are disabled in the txt2img tab.

**Comment by pkuliyi2015** [comment]
How large is the image you are trying to draw? Can you offer a screenshot?

**Comment by RoyDingZF** [comment]
我也遇到这个问题，原本2s的生成t2i图片打开这个拓展就会增加到7s生成

**Comment by guzuligo** [comment]
A simple 512x512. I didn't tick the "Enabled Button". It seems the extension is still executing something even when it is not enabled.

**Comment by pkuliyi2015** [comment]
It is very weird. Technically, you can see from the scripts/tilediffusion.py that I'm unhooking everything if you disable the extension, where the unhooking is just setting 4/5 variables. It shouldn't be that slow, I wonder what has happened.. Please give me time so I can have a try.

**Comment by Kahsolt** [comment]
This should have been fixed with the latest commit, due to unnecessary double `torch_gc()` call.

这个问题在最近的提交中应当已经被，可能的原因是显存释放函数调了两遍。（狗头
