### ISSUE TITLE
I feel that the layered layout function of WebUI is much more difficult to use than that of Comfy UI

### ISSUE THREAD

**Issue by ye-pei-sheng** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#97]
![365235](https://user-images.githubusercontent.com/128130872/229334927-536d527e-1868-4db3-8629-316292e092d0.jpg)
![uxx1](https://user-images.githubusercontent.com/128130872/229334944-1d794e7b-1115-40d2-9517-20093cdb3f6e.png)

I don't even know where to submit the size of the hierarchical layout, and I want a more intuitive interface.

At the same time, I am very grateful to the developers for doing such an important work.

**Comment by pkuliyi2015** [comment]
Thanks for mentioning it, but I have known the ComfyUI's feature so far. The feature comes out around two weeks ago.

You are right. The node-based flow is naturally suitable for compositional drawing, but automatic1111 is extremely confined by the Gradio and is nearly impossible to make such an elegant flow UI without massive hacks.

However, considering that most users are still using automatic1111, you shouldn't expect too much on it. Most of us regard Stable Diffusion as a hobby and just like to draw random things in batches without so much control. And this extension is currently the most similar alternatives to ComfyUI's features, where users can easily try compositional generation with several clicks. It is natural that you cannot get a fine layout, I only offered two layers: background and foreground. And we even cannot control when should we start merging. Meanwhile, the development is solely on my own, no one can help me.

If you like compositional drawing and want to work as a professional to edit each photo, just use ComfyUI please. There are many professionals helping them developing the toolchain.

**Comment by ye-pei-sheng** [comment]
> 感谢您提及它，但到目前为止我已经知道 ComfyUI 的功能。该功能大约在两周前推出。
> 
> 你是对的。基于节点的流程自然适合合成绘制，但 automatic1111 受到 Gradio 的极大限制，如果没有大量的黑客攻击，几乎不可能制作出如此优雅的流程 UI。
> 
> 但是，考虑到大多数用户仍在使用 automatic1111，您不应该对它期望过高。我们大多数人将稳定扩散视为一种爱好，只是喜欢在没有太多控制的情况下批量绘制随机的东西。这个扩展是目前与 ComfyUI 功能最相似的替代品，用户只需单击几下即可轻松尝试合成生成。自然无法获得精细的布局，我只提供了两层：背景和前景。我们甚至无法控制何时开始合并。同时，发展完全靠我自己，没有人可以帮助我。
> 
> 如果您喜欢构图并想作为专业人士编辑每张照片，请使用ComfyUI。有许多专业人士帮助他们开发工具链。

Great jobs are always interlinked and can be learned from each other. Thank you again for your response. I like both WebUI and ComfyUI very much.
