### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by LieDeath** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#99]
happen when interrupt generate process. only with tiled VAE is active. the using commit hash is 1118560 
```
Error completing request
Arguments: ('task(mx77s8zqou9v37e)', "1girl", '', [], 20, 3, False, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 1152, 1152, False, 0.5, 3, 'R-ESRGAN 4x+ Anime6B', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, False, True, True, 0, 1536, 96, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.external_code.ControlNetUnit object at 0x000001B7E17FD1E0>, <scripts.external_code.ControlNetUnit object at 0x000001B7E17FCF40>, <scripts.external_code.ControlNetUnit object at 0x000001B7F3D32710>, False, '', 0.5, True, False, '', 'Lerp', False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, 3, 0, False, False, 0, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, False, False, False, '#000000', '', 5, 24, 12.5, 1000, '', 'DDIM', 0, 64, 64, '', 64, 7.5, 0.42, 'DDIM', 64, 64, 1, 0, 92, True, True, True, False, False, False, 'midas_v21_small', None, False, None, False, None, False, 50, '', False, False, False, False, 'Auto', 0.5, 1, '{inspiration}', None) {}
Traceback (most recent call last):
  File "D:\AI6\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\AI6\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\AI6\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\AI6\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "D:\AI6\stable-diffusion-webui\modules\processing.py", line 655, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "D:\AI6\stable-diffusion-webui\modules\processing.py", line 655, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pkuliyi2015** [comment]
Hello, may I know if there is any guidelines, if the user is intended it to interrupt the generation?

I don’t know what should do on interruption. The webui has no guideline too. I just returned the current variable but it seems to break many things

**Comment by LieDeath** [comment]
> Hello, may I know if there is any guidelines, if the user is intended it to interrupt the generation?
> 
> I don’t know what should do on interruption. The webui has no guideline too. I just returned the current variable but it seems to break many things

can we ask directly to AUTOMATIC1111?

**Comment by LieDeath** [comment]
> Hello, may I know if there is any guidelines, if the user is intended it to interrupt the generation?
> 
> I don’t know what should do on interruption. The webui has no guideline too. I just returned the current variable but it seems to break many things

My Chinese friends said that the AUTOMATIC1111's effectuating method is directly break, but in your repository the tiled VAE, which is return, with 2 layers of cycles. I am not a programmer and be confused with it, and wish that the original discussion could help with you.
A1111的实现是直接break，但是在分块VAE里面用的是return，并且套用了两层循环。
![Screenshot_2023-04-07-12-34-37-122_com tencent mo](https://user-images.githubusercontent.com/115352572/230542752-4ace0e9c-5c51-4c7c-a364-c093f8aa609e.jpg)

**Comment by Hugo-Peng** [comment]
It seems AUTOMATIC1111's WebUI do no interruption in decode stage, so just delete or annotate the two _if_ statements (line 683-684, and 691-692) in method "vae_tile_forward" of class VAEHook in vae_optimize.py, then you will get a blurry image as normal after interruption.
![image](https://user-images.githubusercontent.com/54316932/230565994-1f4e39f3-bf71-4638-834f-4466a56de147.png)

**Comment by Kahsolt** [comment]
Put a conservative fix to avoid this error. If decoding process is interrupted, a possibly pure grey image will be returned ;(

Due to the natural calculation order of tiled vae, you **would not probably** to get a half-decoded image. 
Simple because half-decoded tensors are not valid image in both correct shape and value range.
